"""The skill gazetteer: what a job advert can ask for, and how it spells it.

Separated from the matching logic because it is data, not code, and because
it is meant to grow. Adding a trade means adding a line here; nothing else
in the project changes.

Each entry is ``(id, label, category, *aliases)``. The label is always
usable as an alias, so it is not repeated. Aliases carry the spellings that
actually occur: the German name beside the English one, the abbreviation
beside the full form, and the ASCII spelling beside the umlaut one where
people type both.

Matching is case-insensitive and umlaut-insensitive (see ``normalize``), so
aliases are written in whatever form reads most clearly.

Deliberately absent: names that collide with ordinary words. "Go" and "R"
are real languages, but an advert saying "go live" must not acquire a Go
requirement, so they are reachable through unambiguous aliases only. The
same guard lives in ``skills_lexicon.AMBIGUOUS_ALIASES``.
"""

# --------------------------------------------------------------------------
# Software and IT
# --------------------------------------------------------------------------

IT_SKILLS: tuple[tuple[str, ...], ...] = (
    # --- programming languages ---------------------------------------------
    ("python", "Python", "language"),
    ("csharp", "C#", "language", "c sharp", "csharp"),
    ("cpp", "C++", "language", "cpp"),
    ("clang", "C", "language", "c-programmierung", "ansi c", "embedded c"),
    ("java", "Java", "language"),
    ("javascript", "JavaScript", "language", "js", "ecmascript"),
    ("typescript", "TypeScript", "language", "ts"),
    ("php", "PHP", "language"),
    ("ruby", "Ruby", "language"),
    ("kotlin", "Kotlin", "language"),
    ("swift", "Swift", "language"),
    ("scala", "Scala", "language"),
    ("golang", "Go", "language", "golang", "go-entwicklung", "go developer"),
    ("rlang", "R", "language", "r-programmierung", "sprache r", "r language", "r studio", "rstudio"),
    ("rust", "Rust", "language"),
    ("perl", "Perl", "language"),
    ("abap", "ABAP", "language"),
    ("matlab", "MATLAB", "language", "simulink"),
    ("vba", "VBA", "language", "visual basic for applications", "visual basic", "vb.net"),
    ("dart", "Dart", "language"),
    ("objectivec", "Objective-C", "language", "objective c"),
    ("groovy", "Groovy", "language"),
    ("lua", "Lua", "language"),
    ("elixir", "Elixir", "language", "erlang"),
    ("haskell", "Haskell", "language", "f#", "ocaml"),
    ("assembler", "Assembler", "language", "assemblersprache"),
    ("cobol", "COBOL", "language", "fortran", "pascal", "delphi"),
    ("vhdl", "VHDL", "language", "verilog", "systemverilog"),
    # --- shells and scripting ----------------------------------------------
    ("bash", "Bash", "language", "shell", "shellskripte", "shell scripting", "sh", "zsh"),
    ("powershell", "PowerShell", "language", "power shell", "powershell dsc"),
    ("batch", "Batch", "language", "batch-skripte", "cmd-skripte"),
    # --- .NET ---------------------------------------------------------------
    ("dotnet", ".NET", "framework", "dotnet", ".net core", ".net framework", "net framework"),
    ("aspnet", "ASP.NET", "framework", "asp net", "aspnet core", "asp.net mvc"),
    ("entityframework", "Entity Framework", "framework", "ef core", "entityframework"),
    ("wpf", "WPF", "framework", "windows presentation foundation", "winforms", "windows forms"),
    ("blazor", "Blazor", "framework"),
    ("xamarin", "Xamarin", "framework", "maui", ".net maui"),
    # --- web frontend -------------------------------------------------------
    ("html", "HTML", "web", "html5"),
    ("css", "CSS", "web", "css3", "scss", "sass", "less"),
    ("react", "React", "web", "react.js", "reactjs", "redux", "react hooks"),
    ("angular", "Angular", "web", "angularjs", "rxjs"),
    ("vue", "Vue", "web", "vue.js", "vuejs", "nuxt"),
    ("svelte", "Svelte", "web", "sveltekit"),
    ("nextjs", "Next.js", "web", "nextjs", "remix"),
    ("tailwind", "Tailwind", "web", "tailwind css", "bootstrap", "material ui", "mui"),
    ("jquery", "jQuery", "web"),
    ("bundler", "Webpack", "web", "vite", "rollup", "babel", "esbuild"),
    ("wcag", "Barrierefreiheit", "web", "wcag", "accessibility", "bitv", "aria"),
    # --- web backend --------------------------------------------------------
    ("nodejs", "Node.js", "web", "nodejs", "node js", "express", "nestjs", "deno"),
    ("rest", "REST", "web", "rest-api", "restful", "rest api", "restful api", "openapi", "swagger", "rest apis", "restful apis", "rest schnittstellen", "rest service", "rest services"),
    ("graphql", "GraphQL", "web"),
    ("soap", "SOAP", "web", "wsdl", "xml-schnittstellen"),
    ("grpc", "gRPC", "web", "protobuf", "protocol buffers"),
    ("websocket", "WebSocket", "web", "websockets", "socket.io"),
    ("django", "Django", "web"),
    ("flask", "Flask", "web", "fastapi"),
    ("spring", "Spring", "web", "spring boot", "springboot", "hibernate", "jpa"),
    ("laravel", "Laravel", "web", "symfony", "codeigniter"),
    ("rails", "Ruby on Rails", "web", "rails"),
    ("streamlit", "Streamlit", "web", "dash", "gradio"),
    ("messaging", "Message Broker", "web", "rabbitmq", "kafka", "apache kafka", "activemq", "celery", "redis queue"),
    # --- mobile --------------------------------------------------------------
    ("android", "Android", "mobile", "android sdk", "jetpack compose"),
    ("ios", "iOS", "mobile", "swiftui", "uikit", "xcode"),
    ("flutter", "Flutter", "mobile"),
    ("reactnative", "React Native", "mobile", "ionic", "cordova"),
    # --- databases -----------------------------------------------------------
    ("sql", "SQL", "database", "sql-kenntnisse", "structured query language", "sql-abfragen", "datenbank", "datenbanken", "relationale datenbanken"),
    ("mysql", "MySQL", "database", "mariadb"),
    ("postgresql", "PostgreSQL", "database", "postgres"),
    ("mssql", "Microsoft SQL Server", "database", "ms sql", "mssql", "sql server", "t-sql", "tsql", "ssms"),
    ("oracledb", "Oracle Database", "database", "oracle db", "pl/sql", "plsql"),
    ("db2", "Db2", "database", "sybase", "informix"),
    ("mongodb", "MongoDB", "database", "mongo", "documentdb"),
    ("redis", "Redis", "database", "memcached"),
    ("sqlite", "SQLite", "database"),
    ("elasticsearch", "Elasticsearch", "database", "elastic search", "opensearch", "solr", "lucene"),
    ("bigquery", "BigQuery", "database", "google bigquery"),
    ("snowflake", "Snowflake", "database", "redshift", "synapse"),
    ("nosql", "NoSQL", "database", "cassandra", "dynamodb", "cosmos db", "couchbase"),
    ("graphdb", "Graphdatenbanken", "database", "neo4j", "graph database", "sparql"),
    ("timeseries", "Zeitreihendatenbanken", "database", "influxdb", "timescaledb", "prometheus tsdb"),
    ("datamodeling", "Datenmodellierung", "database", "data modeling", "datenmodell", "datenbankdesign", "normalisierung", "er-modell"),
    ("dbadmin", "Datenbankadministration", "database", "database administration", "dba", "indexoptimierung", "query tuning", "performance tuning"),
    # --- data and analytics --------------------------------------------------
    ("pandas", "pandas", "data", "polars"),
    ("numpy", "NumPy", "data", "scipy"),
    ("scikitlearn", "scikit-learn", "data", "sklearn", "scikit learn", "xgboost", "lightgbm"),
    ("tableau", "Tableau", "data"),
    ("powerbi", "Power BI", "data", "powerbi", "microsoft power bi", "dax", "power query"),
    ("qlik", "Qlik", "data", "qlikview", "qlik sense", "looker", "micro strategy"),
    ("excel", "Excel", "data", "microsoft excel", "ms excel", "pivot-tabellen", "pivottabellen", "sverweis", "vlookup"),
    ("spark", "Apache Spark", "data", "pyspark", "spark", "databricks", "hadoop", "hive"),
    ("etl", "ETL", "data", "etl-prozesse", "datenpipelines", "data pipeline", "elt", "ssis", "talend", "airflow", "apache airflow", "dbt"),
    ("datawarehouse", "Data Warehouse", "data", "dwh", "data lake", "lakehouse", "star schema", "sternschema"),
    ("statistics", "Statistik", "data", "statistics", "deskriptive statistik", "statistische analyse", "hypothesentest", "regression"),
    ("dataviz", "Datenvisualisierung", "data", "data visualization", "dashboards", "reporting", "ssrs", "berichtswesen"),
    ("dataquality", "Datenqualität", "data", "data quality", "data cleaning", "datenbereinigung", "stammdatenpflege", "datenvalidierung", "datenpflege"),
    ("datagovernance", "Data Governance", "data", "datenkatalog", "data lineage", "mdm", "stammdatenmanagement"),
    # --- AI / ML --------------------------------------------------------------
    ("machinelearning", "Maschinelles Lernen", "ai", "machine learning", "ml", "maschinelles lernen", "predictive modeling", "ml engineer", "ml ops", "ml-modelle"),
    ("deeplearning", "Deep Learning", "ai", "neuronale netze", "neural networks", "tiefes lernen", "cnn", "transformer"),
    ("llm", "Große Sprachmodelle", "ai", "large language models", "llm", "llms", "sprachmodelle", "gpt", "chatgpt"),
    ("nlp", "NLP", "ai", "natural language processing", "computerlinguistik", "sprachverarbeitung", "texterkennung"),
    ("computervision", "Computer Vision", "ai", "bildverarbeitung", "bilderkennung", "ocr", "opencv"),
    ("tensorflow", "TensorFlow", "ai", "keras"),
    ("pytorch", "PyTorch", "ai", "huggingface", "hugging face", "transformers"),
    ("ai_general", "Künstliche Intelligenz", "ai", "artificial intelligence", "ki", "ai"),
    ("aiagents", "KI-Agenten", "ai", "ai agents", "agentic", "ki agenten", "langchain"),
    ("ollama", "Ollama", "ai", "llama.cpp", "vllm"),
    ("rag", "RAG", "ai", "retrieval augmented generation", "vektordatenbank", "vector database", "embeddings"),
    ("promptengineering", "Prompt Engineering", "ai", "prompting"),
    ("mlops", "MLOps", "ai", "mlflow", "modell-deployment", "model deployment", "feature store"),
    # --- infrastructure --------------------------------------------------------
    ("linux", "Linux", "infra", "unix", "ubuntu", "debian", "red hat", "rhel", "centos", "suse", "linux-administration"),
    ("windowsserver", "Windows Server", "infra", "windows-server", "windows server 2022", "server 2019"),
    ("docker", "Docker", "infra", "container", "containerisierung", "docker compose", "podman", "containerization"),
    ("kubernetes", "Kubernetes", "infra", "k8s", "openshift", "helm", "rancher", "argocd", "argo cd"),
    ("ansible", "Ansible", "infra"),
    ("terraform", "Terraform", "infra", "infrastructure as code", "iac", "pulumi", "cloudformation", "bicep"),
    ("puppet", "Puppet", "infra", "chef", "saltstack", "chef infra", "chef automate", "chef server"),
    ("vmware", "VMware", "infra", "vsphere", "esxi", "virtualisierung", "virtualization", "vcenter"),
    ("proxmox", "Proxmox", "infra", "kvm", "xen"),
    ("hyperv", "Hyper-V", "infra", "hyperv"),
    ("citrix", "Citrix", "infra", "terminalserver", "remote desktop services", "rds", "vdi"),
    ("truenas", "TrueNAS", "infra", "freenas", "nas", "nas-systeme", "san", "storage", "speicherverwaltung", "san storage"),
    ("nginx", "Nginx", "infra", "apache", "webserver", "iis", "haproxy", "traefik"),
    ("aws", "AWS", "cloud", "amazon web services", "ec2", "s3", "lambda", "eks", "ecs"),
    ("azure", "Azure", "cloud", "microsoft azure", "azure devops", "azure functions", "entra"),
    ("gcp", "Google Cloud", "cloud", "gcp", "google cloud platform"),
    ("cloud_general", "Cloud", "cloud", "cloud-technologien", "cloud computing", "hybrid cloud", "multi-cloud"),
    ("backup", "Backup", "infra", "datensicherung", "restore", "disaster recovery", "veeam", "notfallkonzept"),
    ("monitoring", "Monitoring", "infra", "überwachung", "prometheus", "grafana", "nagios", "zabbix", "checkmk", "icinga"),
    ("observability", "Observability", "infra", "elk", "elastic stack", "splunk", "datadog", "new relic", "sentry", "loki", "logging"),
    ("intune", "Intune", "infra", "sccm", "mecm", "wsus", "gruppenrichtlinien", "group policy", "mdm-verwaltung", "endpoint management"),
    ("embedded", "Embedded Systems", "infra", "mikrocontroller", "microcontroller", "arduino", "raspberry pi", "fpga", "rtos", "bare metal"),
    ("fieldbus", "Feldbus", "infra", "can-bus", "modbus", "profinet", "profibus", "opc ua", "mqtt", "iot", "industrie 4.0"),
    # --- networking -------------------------------------------------------------
    ("networking", "Netzwerk", "network", "netzwerke", "networking", "netzwerktechnik", "lan", "wan", "netzwerkadministration"),
    ("tcpip", "TCP/IP", "network", "tcp ip", "subnetting", "ipv6"),
    ("dns", "DNS", "network", "dhcp", "namensauflösung"),
    ("vpn", "VPN", "network", "ipsec", "wireguard", "openvpn"),
    ("firewall", "Firewall", "network", "firewalls", "fortigate", "pfsense", "sophos", "palo alto", "checkpoint"),
    ("routing", "Routing", "network", "switching", "bgp", "ospf", "vlan", "mpls", "sd-wan", "spanning tree"),
    ("ciscohw", "Cisco", "network", "juniper", "hpe aruba", "ubiquiti", "ccna", "ccnp"),
    ("wlan", "WLAN", "network", "wifi", "wi-fi", "access points", "funknetz"),
    ("activedirectory", "Active Directory", "network", "ad", "ldap", "entra id", "azure ad", "domänencontroller"),
    ("exchange", "Exchange", "network", "microsoft exchange", "outlook", "mail-server", "smtp", "postfix"),
    ("m365", "Microsoft 365", "network", "office 365", "o365", "ms office", "microsoft office", "sharepoint online", "teams", "microsoft teams", "ms teams"),
    ("telefonie", "Telefonie", "network", "voip", "sip", "tk-anlage", "unified communications"),
    # --- security ---------------------------------------------------------------
    ("security", "IT-Sicherheit", "security", "it-security", "informationssicherheit", "cyber security", "cybersecurity", "sicherheitskonzepte"),
    ("datenschutz", "Datenschutz", "security", "dsgvo", "gdpr", "datenschutzgrundverordnung", "privacy"),
    ("pentest", "Penetrationstest", "security", "pentest", "penetration testing", "schwachstellenanalyse", "vulnerability", "burp suite", "nessus", "metasploit"),
    ("siem", "SIEM", "security", "soc", "security operations", "incident response", "threat detection", "ids", "ips"),
    ("iam", "Identity Management", "security", "iam", "berechtigungsverwaltung", "rechteverwaltung", "single sign-on", "sso", "oauth", "saml", "keycloak", "pki", "zertifikatsverwaltung"),
    ("isms", "ISO 27001", "security", "isms", "bsi grundschutz", "it-grundschutz", "nis2", "tisax", "sicherheitsaudit"),
    ("kryptographie", "Kryptographie", "security", "verschlüsselung", "encryption", "tls", "hsm"),
    # --- tools and process -------------------------------------------------------
    ("git", "Git", "tool", "github", "gitlab", "bitbucket", "versionsverwaltung", "version control", "svn", "azure repos"),
    ("cicd", "CI/CD", "method", "ci cd", "continuous integration", "continuous delivery", "jenkins", "github actions", "gitlab ci", "teamcity", "bamboo", "deployment-pipeline"),
    ("jira", "Jira", "tool", "confluence", "atlassian", "azure boards", "youtrack"),
    ("ticketsystem", "Ticketsystem", "tool", "ticketing", "servicedesk", "service desk", "helpdesk", "otrs", "jira service management", "zendesk", "freshdesk"),
    ("n8n", "n8n", "tool", "zapier", "make.com", "power automate", "workflow-tools"),
    ("ide", "Visual Studio", "tool", "visual studio code", "vs code", "intellij", "pycharm", "eclipse", "rider", "netbeans"),
    # --- testing ------------------------------------------------------------------
    ("testing", "Testing", "method", "softwaretest", "qualitätssicherung", "quality assurance", "qa", "testautomatisierung", "test automation", "testfälle", "testkonzepte", "testmanagement"),
    ("tdd", "TDD", "method", "test driven development", "unit tests", "unittests", "pytest", "junit", "nunit", "xunit", "jest", "mocha", "testng"),
    ("e2etesting", "End-to-End-Tests", "method", "selenium", "cypress", "playwright", "appium", "robot framework", "ui-tests"),
    ("apitesting", "API-Tests", "method", "postman", "soapui", "rest assured"),
    ("loadtesting", "Lasttests", "method", "jmeter", "loadrunner", "performancetests", "k6", "gatling"),
    ("istqb", "ISTQB", "method", "certified tester"),
    # --- methods --------------------------------------------------------------------
    ("scrum", "Scrum", "method", "agile", "agil", "kanban", "safe", "sprint", "daily", "retrospektive", "scrum master", "product owner", "scaled agile", "safe framework", "daily standup", "daily stand-up"),
    ("devops", "DevOps", "method", "sre", "site reliability", "platform engineering"),
    ("itil", "ITIL", "method", "itsm", "cobit", "service management", "incident management", "problem management"),
    ("waterfall", "Wasserfallmodell", "method", "v-modell", "v-modell xt", "waterfall", "prince2", "pmi", "pmp", "ipma"),
    ("oop", "Objektorientierte Programmierung", "method", "object oriented programming", "oop", "objektorientierung", "vererbung"),
    ("microservices", "Microservices", "method", "microservice", "mikroservices", "serverless", "event-driven", "ereignisgesteuert"),
    ("designpatterns", "Design Patterns", "method", "entwurfsmuster", "clean code", "solid", "refactoring", "code review", "pair programming", "solid principles", "solid-prinzipien"),
    ("uml", "UML", "method", "bpmn", "modellierung", "sequenzdiagramm", "aktivitätsdiagramm", "archimate"),
    ("softwarearchitektur", "Softwarearchitektur", "method", "software architecture", "systemarchitektur", "architekturentscheidungen", "domain driven design", "ddd"),
    ("requirements", "Anforderungsanalyse", "method", "requirements engineering", "anforderungsmanagement", "lastenheft", "pflichtenheft", "user stories", "epics"),
    ("documentation", "Dokumentation", "method", "technische dokumentation", "documentation", "betriebshandbuch", "wiki-pflege"),
    ("automation", "Automatisierung", "method", "automation", "prozessautomatisierung", "process automation", "workflow automation", "rpa", "skripting"),
    # --- ERP, CRM, CMS ------------------------------------------------------------------
    ("sap", "SAP", "business", "sap erp", "s/4hana", "sap fi", "sap co", "sap mm", "sap sd", "sap hcm", "sap basis"),
    ("dynamics", "Microsoft Dynamics", "business", "dynamics 365", "navision", "business central", "axapta"),
    ("erp_other", "ERP-Systeme", "business", "odoo", "abas", "proalpha", "infor", "erp-system", "warenwirtschaftssystem"),
    ("salesforce", "Salesforce", "business", "crm", "crm-systeme", "hubspot", "pipedrive"),
    ("cms", "CMS", "business", "wordpress", "typo3", "drupal", "joomla", "contentful", "content management system"),
    ("ecommerce", "E-Commerce", "business", "shopware", "magento", "shopify", "woocommerce", "onlineshop"),
    ("itwo", "iTWO", "business", "rib itwo", "nevaris", "bausoftware"),
)


# --------------------------------------------------------------------------
# Everything else people are hired to do
# --------------------------------------------------------------------------

PROFESSION_SKILLS: tuple[tuple[str, ...], ...] = (
    # --- medicine and health -------------------------------------------------
    ("approbation", "Approbation", "health", "facharzt", "facharztausbildung", "assistenzarzt", "oberarzt", "medical licence"),
    ("diagnostik", "Diagnostik", "health", "anamnese", "befundung", "differentialdiagnose", "diagnosis"),
    ("chirurgie", "Chirurgie", "health", "operationen", "op-assistenz", "surgery", "op-saal", "instrumentieren"),
    ("innere", "Innere Medizin", "health", "kardiologie", "gastroenterologie", "onkologie", "neurologie", "pädiatrie", "gynäkologie", "orthopädie", "urologie", "dermatologie", "psychiatrie"),
    ("anaesthesie", "Anästhesie", "health", "narkose", "intensivmedizin", "beatmung", "anesthesia"),
    ("radiologie", "Radiologie", "health", "röntgen", "mrt", "ct", "sonographie", "ultraschall", "bildgebung", "radiography", "medizinisch-technische radiologieassistenz"),
    ("notfallmedizin", "Notfallmedizin", "health", "notaufnahme", "emergency medicine", "triage", "reanimation"),
    ("patientenversorgung", "Patientenversorgung", "health", "patientenbetreuung", "visite", "patient care", "aufklärungsgespräche"),
    ("zahnmedizin", "Zahnmedizin", "health", "zahnarzt", "prophylaxe", "dental", "kieferorthopädie"),
    ("apotheke", "Apotheke", "health", "pharmazie", "arzneimittel", "pharmacy", "medikationsberatung"),
    ("veterinaer", "Veterinärmedizin", "health", "tierarzt", "tiermedizin", "veterinary"),
    ("hebamme", "Geburtshilfe", "health", "hebamme", "midwifery", "wochenbett"),
    ("mfa", "Medizinische Fachangestellte", "health", "mfa", "arzthelferin", "praxisorganisation", "blutentnahme", "ekg", "terminvergabe", "abrechnung ebm"),
    ("abrechnung_med", "Medizinische Abrechnung", "health", "goä", "ebm", "drg", "kodierung", "medical coding", "kassenabrechnung"),
    # --- care and social work -------------------------------------------------
    ("pflege", "Pflege", "care", "altenpflege", "krankenpflege", "nursing", "pflegefachkraft", "gesundheits- und krankenpfleger"),
    ("pflegedoku", "Pflegedokumentation", "care", "pflegeplanung", "care documentation", "pflegeprozess", "pflegedokumentation", "pflegeanamnese", "care planning", "strukturierte informationssammlung"),
    ("wundmanagement", "Wundmanagement", "care", "wundversorgung", "wound care", "dekubitusprophylaxe", "dekubitus", "chronische wunden", "wundexperte"),
    ("medikamentengabe", "Medikamentengabe", "care", "medikamentenmanagement", "medication management", "injektionen"),
    ("erstehilfe", "Erste Hilfe", "care", "first aid", "notfallmanagement", "reanimation", "defibrillator"),
    ("hygiene", "Hygiene", "care", "hygienevorschriften", "desinfektion", "disinfection", "hygienestandards", "infektionsschutz"),
    ("betreuung", "Betreuung", "care", "personenbetreuung", "tagesbetreuung", "support work", "eingliederungshilfe", "assistenz", "behindertenhilfe", "sgb ix", "bthg"),
    ("therapie", "Therapie", "care", "massage", "dysphagie", "wellnessmassage", "massage therapy", "wellnessanwendungen"),
    ("sozialarbeit", "Soziale Arbeit", "care", "sozialpädagogik", "sozialarbeit", "social work", "beratungsgespräche", "case management", "jugendhilfe", "sozialarbeiter", "beratungsstelle", "einzelfallhilfe", "erzieherische hilfen", "sgb viii", "familienhilfe", "jugendamt", "youth work"),
    ("labor", "Labor", "health", "labortechnik", "laboratory", "probenahme", "mta", "analytik", "laborwerte"),
    # --- education and religion ------------------------------------------------
    ("paedagogik", "Pädagogik", "education", "erziehung", "frühpädagogik", "pedagogy", "erzieher", "erzieherin", "kita", "kindergarten"),
    ("unterricht", "Unterricht", "education", "lehrtätigkeit", "didaktik", "methodik", "teaching", "lehrer", "dozent", "nachhilfe", "seminare", "lehrkraft", "unterrichtsplanung", "lehrprobe", "differenzierung", "tutoring", "lernförderung", "hausaufgabenbetreuung"),
    ("bildungsplan", "Bildungsplan", "education", "bildungspläne", "curriculum", "lehrplan", "rahmenplan"),
    ("elternarbeit", "Elternarbeit", "education", "erziehungspartnerschaft", "parent communication", "elterngespräche"),
    ("gruppenleitung", "Gruppenleitung", "education", "gruppenarbeit", "group work", "anleitung", "klassenführung"),
    ("inklusion", "Inklusion", "education", "integration", "heilpädagogik", "sonderpädagogik", "förderbedarf"),
    ("seelsorge", "Seelsorge", "religion", "pastoral", "pastoralarbeit", "spiritual care", "beichte", "geistliche begleitung"),
    ("gottesdienst", "Gottesdienst", "religion", "liturgie", "predigt", "andacht", "worship", "sakramente", "kirchenmusik"),
    ("gemeindearbeit", "Gemeindearbeit", "religion", "gemeindeleitung", "jugendarbeit", "kirchengemeinde", "ehrenamtskoordination"),
    ("theologie", "Theologie", "religion", "religionspädagogik", "theology", "exegese", "kirchenrecht"),
    # --- law, consulting, public sector ------------------------------------------
    ("rechtsberatung", "Rechtsberatung", "legal", "juristische beratung", "legal advice", "gutachten", "rechtsprüfung"),
    ("vertragsrecht", "Vertragsrecht", "legal", "vertragsgestaltung", "vertragsverhandlung", "contract law", "agb", "nda"),
    ("prozessfuehrung", "Prozessführung", "legal", "litigation", "schriftsätze", "gerichtstermine", "mandantenbetreuung"),
    ("rechtsgebiete", "Rechtsgebiete", "legal", "arbeitsrecht", "labour law", "labor law", "tarifrecht", "handelsrecht", "gesellschaftsrecht", "familienrecht", "strafrecht", "mietrecht", "baurecht", "verwaltungsrecht", "sozialrecht", "kündigungsschutz", "arbeitsvertrag", "betriebsrat", "betriebsverfassungsgesetz", "tarifvertrag"),
    ("notariat", "Notariat", "legal", "beurkundung", "grundbuch", "rechtsanwaltsfachangestellte", "reno", "kanzleiorganisation"),
    ("unternehmensberatung", "Unternehmensberatung", "consulting", "consulting", "prozessberatung", "management consulting", "strategieberatung", "organisationsentwicklung", "prozessoptimierung", "business process", "ist-analyse", "soll-konzept", "reorganisation"),
    ("changemanagement", "Change Management", "consulting", "veränderungsmanagement", "transformation", "stakeholder-management", "moderation", "workshops"),
    ("prozessanalyse", "Prozessanalyse", "consulting", "prozessoptimierung", "process improvement", "lean", "six sigma", "kaizen", "kvp", "wertstromanalyse"),
    ("praesentation", "Präsentationen", "consulting", "presentation skills", "powerpoint", "pitch", "kundenpräsentation"),
    ("verwaltung_public", "Öffentliche Verwaltung", "public", "behörde", "bürgerbüro", "verwaltungsfachangestellte", "amtsleitung", "public administration", "ausschreibungsrecht", "vergaberecht", "vob"),
    # --- finance, banking, insurance -----------------------------------------------
    ("buchhaltung", "Buchhaltung", "finance", "finanzbuchhaltung", "rechnungswesen", "bookkeeping", "accounting", "kreditorenbuchhaltung", "debitorenbuchhaltung", "anlagenbuchhaltung"),
    ("lohnbuchhaltung", "Lohnbuchhaltung", "finance", "entgeltabrechnung", "gehaltsabrechnung", "payroll", "lohnsteuer", "sozialversicherung"),
    ("datev", "DATEV", "finance", "lexware", "addison", "sage", "agenda"),
    ("bilanzierung", "Bilanzierung", "finance", "jahresabschluss", "hgb", "ifrs", "financial statements", "monatsabschluss", "konzernabschluss"),
    ("steuerrecht", "Steuerrecht", "finance", "umsatzsteuer", "tax law", "steuererklärung", "steuerberatung", "körperschaftsteuer"),
    ("controlling", "Controlling", "finance", "kostenrechnung", "budgetplanung", "forecasting", "kennzahlen", "kpi", "abweichungsanalyse", "wirtschaftlichkeitsrechnung"),
    ("mahnwesen", "Mahnwesen", "finance", "forderungsmanagement", "dunning", "inkasso", "zahlungsverkehr"),
    ("treasury", "Treasury", "finance", "liquiditätsplanung", "cash management", "finanzierung", "kapitalmarkt"),
    ("bankwesen", "Bankwesen", "banking", "bankkaufmann", "bankkauffrau", "banking", "kontoführung", "filialgeschäft", "bankberatung"),
    ("kreditgeschaeft", "Kreditgeschäft", "banking", "kreditanalyse", "baufinanzierung", "firmenkundenkredit", "lending", "bonitätsprüfung", "rating"),
    ("anlageberatung", "Anlageberatung", "banking", "wertpapiere", "investment", "portfoliomanagement", "vermögensberatung", "fonds", "depot", "börse", "investmentfonds", "wertpapierdepot"),
    ("compliance_fin", "Compliance", "banking", "geldwäscheprävention", "kyc", "know your customer", "aml", "mifid", "wphg", "regulatorik", "meldewesen"),
    ("risikomanagement", "Risikomanagement", "banking", "risk management", "risikoanalyse", "basel", "solvency", "basel iii", "basel ii"),
    ("versicherung", "Versicherung", "insurance", "versicherungskaufmann", "insurance", "policen", "tarifierung", "versicherungsvertrieb"),
    ("schadenregulierung", "Schadenregulierung", "insurance", "schadenbearbeitung", "claims", "leistungsprüfung", "sachverständigengutachten"),
    # --- sales, retail, marketing ---------------------------------------------------
    ("kundenberatung", "Kundenberatung", "sales", "kundenbetreuung", "customer service", "kundenkontakt", "beratung", "kundendienst", "kundenservice"),
    ("verkauf", "Verkauf", "sales", "vertrieb", "sales", "verkaufsgespräche", "verkaufsberatung", "abschlussstärke", "vertriebsaußendienst"),
    ("keyaccount", "Key Account Management", "sales", "key account", "großkundenbetreuung", "account management", "b2b", "b2c", "bestandskundenpflege"),
    ("akquise", "Akquise", "sales", "neukundengewinnung", "lead generation", "kaltakquise", "leadgenerierung", "telefonakquise"),
    ("angebotserstellung", "Angebotserstellung", "sales", "angebotskalkulation", "quotation", "ausschreibungen", "auftragsabwicklung", "auftragsbearbeitung"),
    ("vertriebssteuerung", "Vertriebssteuerung", "sales", "umsatzverantwortung", "sales forecast", "pipeline management", "gebietsverantwortung", "vertriebsziele"),
    ("kasse", "Kassiertätigkeit", "retail", "kassensystem", "kassieren", "cash register", "checkout", "kassenabschluss"),
    ("warenpraesentation", "Warenpräsentation", "retail", "warenverräumung", "merchandising", "regalpflege", "visual merchandising", "warenpräsentation", "bestandspflege", "schaufenstergestaltung", "warendekoration", "verkaufsraumgestaltung"),
    ("filialleitung", "Filialleitung", "retail", "marktleitung", "storemanagement", "store manager", "personaleinsatzplanung", "umsatzsteuerung", "umsatzverantwortung"),
    ("inventur", "Inventur", "retail", "bestandskontrolle", "stocktaking", "warenwirtschaft", "bestellwesen"),
    ("reklamation", "Reklamationsbearbeitung", "sales", "beschwerdemanagement", "complaint handling", "retourenbearbeitung"),
    ("marketing", "Marketing", "marketing", "onlinemarketing", "online marketing", "digital marketing", "kampagnen", "marketingstrategie", "markenführung", "branding"),
    ("seo", "SEO", "marketing", "sea", "suchmaschinenoptimierung", "google ads", "adwords", "ppc", "performance marketing"),
    ("socialmedia", "Social Media", "marketing", "social media marketing", "instagram", "linkedin", "tiktok", "community management", "redaktionsplan"),
    ("contentmarketing", "Content Marketing", "marketing", "contenterstellung", "copywriting", "texten", "newsletter", "e-mail-marketing", "blogbeiträge"),
    ("webanalyse", "Webanalyse", "marketing", "google analytics", "matomo", "tracking", "conversion", "a/b-tests"),
    ("pr", "Öffentlichkeitsarbeit", "marketing", "public relations", "pressearbeit", "pressemitteilungen", "unternehmenskommunikation"),
    # --- design, media, creative -------------------------------------------------------
    ("grafikdesign", "Grafikdesign", "design", "graphic design", "mediengestaltung", "layout", "typografie", "typography", "satz", "druckvorstufe", "reinzeichnung", "schriftsatz"),
    ("adobe", "Adobe Creative Suite", "design", "photoshop", "illustrator", "indesign", "after effects", "premiere", "lightroom"),
    ("uiux", "UI/UX", "design", "ux", "ui design", "usability", "wireframes", "prototyping", "user research", "design system"),
    ("figma", "Figma", "design", "adobe xd", "sketch", "invision"),
    ("corporatedesign", "Corporate Design", "design", "brand design", "styleguide", "logoentwicklung", "gestaltungsrichtlinien"),
    ("illustration", "Illustration", "design", "zeichnen", "storyboard", "konzeptzeichnung"),
    ("motiondesign", "Motion Design", "design", "animation", "3d-animation", "videoanimation", "compositing"),
    ("dreid", "3D-Modellierung", "design", "3d modelling", "blender", "maya", "3ds max", "cinema 4d", "rendering", "texturing", "autodesk maya"),
    ("houdini", "Houdini", "design", "sidefx houdini", "3d-simulation", "vfx", "partikelsimulation"),
    ("fotografie", "Fotografie", "media", "photography", "bildbearbeitung", "fotoshooting", "studiofotografie"),
    ("videoproduktion", "Videoproduktion", "media", "videoschnitt", "video editing", "kamera", "filmproduktion", "livestream", "streaming"),
    ("tontechnik", "Tontechnik", "media", "audiotechnik", "sound design", "mischpult", "beschallung", "mikrofonierung"),
    ("veranstaltungstechnik", "Veranstaltungstechnik", "media", "bühnentechnik", "lichttechnik", "event technology", "rigging"),
    ("redaktion", "Redaktion", "media", "journalismus", "recherche", "lektorat", "korrektorat", "editing", "redaktionelle arbeit"),
    ("uebersetzung", "Übersetzung", "media", "translation", "dolmetschen", "interpreting", "lokalisierung", "localisation", "cat-tools", "trados"),
    # --- engineering and architecture ---------------------------------------------------
    ("konstruktion", "Konstruktion", "engineering", "design engineering", "bauteilkonstruktion", "entwicklungskonstruktion", "produktentwicklung"),
    ("cad", "CAD", "engineering", "autocad", "solidworks", "catia", "inventor", "creo", "nx", "solid edge"),
    ("fem", "FEM-Berechnung", "engineering", "finite elemente", "simulation", "strukturanalyse", "cfd", "strömungssimulation"),
    ("statik", "Statik", "engineering", "tragwerksplanung", "structural analysis", "lastannahmen", "bemessung"),
    ("projektierung", "Projektierung", "engineering", "anlagenplanung", "auslegung", "spezifikation"),
    ("inbetriebnahme", "Inbetriebnahme", "engineering", "commissioning", "anlagenoptimierung", "störungsbehebung", "serviceeinsätze"),
    ("normen", "Normen und Richtlinien", "engineering", "din", "iso", "en-normen", "vde", "ce-kennzeichnung", "maschinenrichtlinie", "standards compliance"),
    ("messtechnik", "Messtechnik", "engineering", "prüftechnik", "kalibrierung", "toleranzen", "koordinatenmessgerät"),
    ("qualitaetsmanagement", "Qualitätsmanagement", "engineering", "quality management", "iso 9001", "fmea", "8d-report", "apqp", "ppap", "qm-system", "auditvorbereitung"),
    ("prototypenbau", "Prototypenbau", "engineering", "musterbau", "versuchsaufbau", "prototyping engineering"),
    ("architektur", "Architektur", "architecture", "architect", "hochbau", "entwurfsplanung", "gebäudeplanung", "architekturbüro"),
    ("bauplanung", "Bauplanung", "architecture", "genehmigungsplanung", "ausführungsplanung", "werkplanung", "leistungsphasen", "bauantrag"),
    ("bauleitung", "Bauleitung", "architecture", "site management", "baustellenkoordination", "bauüberwachung", "abnahmen", "baustellenleitung"),
    ("bim", "BIM", "architecture", "building information modeling", "revit", "archicad", "allplan", "vectorworks", "ifc"),
    ("ausschreibung", "Ausschreibung", "architecture", "hoai", "leistungsphasen", "vergabe", "lv-erstellung", "leistungsverzeichnis", "kostenschätzung", "kostenkontrolle", "nachtragsmanagement"),
    ("stadtplanung", "Stadtplanung", "architecture", "urban planning", "bauleitplanung", "bebauungsplan", "landschaftsarchitektur"),
    # --- construction and trades ------------------------------------------------------------
    ("montage", "Montage", "trade", "demontage", "assembly", "baugruppenmontage", "endmontage", "vormontage", "fließbandmontage"),
    ("schweissen", "Schweißen", "trade", "wig", "mag", "mig", "welding", "schweisstechnik", "schweißerprüfung", "löten", "hartlöten", "mag schweissen", "mag-schweissen", "wig schweissen"),
    ("elektroinstallation", "Elektroinstallation", "trade", "elektromontage", "schaltschrankbau", "electrical installation", "elektriker", "elektroniker", "verkabelung", "elektrotechnik"),
    ("sps", "SPS", "trade", "speicherprogrammierbare steuerung", "siemens s7", "plc", "tia portal", "steuerungstechnik", "automatisierungstechnik"),
    ("hydraulik", "Hydraulik", "trade", "pneumatik", "hydraulics", "pneumatics", "antriebstechnik"),
    ("cnc", "CNC", "trade", "cnc-fräsen", "cnc-drehen", "zerspanung", "cnc machining", "drehen", "fräsen", "schleifen"),
    ("sanitaer", "Sanitär", "trade", "heizung", "klima", "shk", "lüftung", "plumbing", "hvac", "anlagenmechaniker"),
    ("technischezeichnung", "Technische Zeichnungen", "trade", "technical drawings", "schaltpläne", "blueprints", "stücklisten", "zeichnungslesen"),
    ("maurer", "Maurerarbeiten", "construction", "beton", "schalung", "bewehrung", "mauerwerk", "masonry", "hochbau-ausführung"),
    ("trockenbau", "Trockenbau", "construction", "innenausbau", "drywall", "dämmung", "estrich"),
    ("dach", "Dachdeckerarbeiten", "construction", "dachdecker", "abdichtung", "roofing"),
    ("fliesen", "Fliesenlegerarbeiten", "construction", "fliesenleger", "bodenbelag", "tiling", "parkett"),
    ("maler", "Malerarbeiten", "construction", "maler", "lackierer", "painting", "tapezieren", "spachteln"),
    ("geruestbau", "Gerüstbau", "construction", "scaffolding", "gerüstmontage"),
    ("tiefbau", "Tiefbau", "construction", "kanalbau", "straßenbau", "erdarbeiten", "civil engineering", "rohrleitungsbau"),
    ("baumaschinen", "Baumaschinen", "construction", "bagger", "radlader", "baumaschinenführer", "kranführer", "kranschein"),
    ("kfz", "Kfz-Technik", "automotive", "fahrzeugtechnik", "kfz-mechatroniker", "automotive", "motorinstandsetzung", "fahrwerk", "bremsen"),
    ("kfzdiagnose", "Fahrzeugdiagnose", "automotive", "diagnosegerät", "fehlerauslese", "hu", "au", "abgasuntersuchung", "hauptuntersuchung"),
    ("lackierung", "Fahrzeuglackierung", "automotive", "karosseriebau", "unfallinstandsetzung", "smart repair", "lackiererei", "fahrzeuglackierung", "body repair", "spenglerei"),
    # --- logistics and driving ---------------------------------------------------------------
    ("fahrerkarte", "Fahrerkarte", "logistics", "bkrfqg", "berufskraftfahrerqualifikation", "modul 95", "schlüsselzahl 95", "fahrpersonalrecht", "lenkzeiten"),
    ("gefahrgut", "Gefahrgut", "logistics", "adr", "adr-schein", "dangerous goods", "gefahrgutbeauftragter"),
    ("stapler", "Staplerschein", "logistics", "gabelstapler", "flurförderzeug", "forklift", "hubwagen", "schubmaststapler"),
    ("kommissionierung", "Kommissionierung", "logistics", "picking", "packen", "versandvorbereitung", "wareneingang", "warenausgang"),
    ("ladungssicherung", "Ladungssicherung", "logistics", "load securing", "verladung", "be- und entladung"),
    ("lager", "Lagerwirtschaft", "logistics", "lagerverwaltung", "lagerhaltung", "warehouse", "bestandsführung", "lagerlogistik", "fachkraft für lagerlogistik", "warenannahme", "wareneingangskontrolle"),
    ("disposition", "Disposition", "logistics", "tourenplanung", "routenplanung", "dispatching", "fuhrparkmanagement", "speditionsabwicklung"),
    ("zoll", "Zollabwicklung", "logistics", "customs", "außenhandel", "export", "import", "atlas", "incoterms"),
    ("supplychain", "Supply Chain", "logistics", "lieferkette", "materialwirtschaft", "bedarfsplanung", "logistikplanung"),
    ("personenbefoerderung", "Personenbeförderung", "logistics", "p-schein", "busfahrer", "taxischein", "fahrgastbetreuung"),
    ("luftfahrt", "Luftfahrt", "aviation", "flugbetrieb", "aviation", "pilotenlizenz", "atpl", "ppl", "cabin crew", "flugbegleiter", "luftsicherheit", "part-145", "easa"),
    ("schifffahrt", "Schifffahrt", "logistics", "nautik", "maritime", "hafenlogistik", "seefracht"),
    ("bahn", "Bahnbetrieb", "logistics", "triebfahrzeugführer", "rangieren", "eisenbahn", "schienenverkehr"),
    # --- hospitality and food ------------------------------------------------------------------
    ("kueche", "Küche", "hospitality", "kuechenerfahrung", "zubereitung", "speisenzubereitung", "kitchen", "food preparation", "koch", "köchin", "gastronomie", "à la carte", "a la carte", "beikoch", "chef de partie"),
    ("haccp", "HACCP", "hospitality", "lebensmittelhygiene", "food safety", "lebensmittelrecht"),
    ("service_gastro", "Service", "hospitality", "servicekraft", "bedienung", "gastronomieservice", "waiting tables", "restaurantfachmann", "gästebetreuung", "kellnern", "restaurantfachfrau", "waiting staff", "chef de rang"),
    ("barista", "Barista", "hospitality", "bar", "cocktails", "bartender", "barkeeper", "getränkekunde", "barmixer", "bartending"),
    ("kalkulation", "Kalkulation", "hospitality", "speisenkalkulation", "wareneinsatz", "costing", "menüplanung"),
    ("bankett", "Bankett", "hospitality", "catering", "veranstaltungsgastronomie", "events", "eventmanagement", "veranstaltungsplanung", "messeorganisation"),
    ("housekeeping", "Housekeeping", "hospitality", "zimmerreinigung", "etagenservice", "wäschemanagement"),
    ("rezeption", "Rezeption", "hospitality", "empfang", "front office", "check-in", "reception", "hotelsoftware", "opera pms", "reservierung"),
    ("baeckerei", "Bäckerei", "hospitality", "konditorei", "backwaren", "patisserie", "fleischerei", "metzgerei", "lebensmittelhandwerk"),
    # --- cleaning and facility -------------------------------------------------------------------
    ("reinigung", "Reinigung", "facility", "unterhaltsreinigung", "grundreinigung", "glasreinigung", "gebäudereinigung", "cleaning", "sonderreinigung", "reinigungskraft", "raumpflege", "büroreinigung", "treppenhausreinigung"),
    ("reinigungsmittel", "Reinigungsmittel", "facility", "reinigungschemie", "dosierung", "cleaning agents", "pflegemittel"),
    ("reinigungsmaschinen", "Reinigungsmaschinen", "facility", "scheuersaugmaschine", "bodenreinigungsmaschine", "cleaning machines", "einscheibenmaschine"),
    ("hausmeister", "Hausmeistertätigkeiten", "facility", "hausmeister", "facility management", "haustechnik", "gebäudetechnik", "kleinreparaturen", "objektbetreuung"),
    ("gartenpflege", "Gartenpflege", "facility", "grünpflege", "landschaftspflege", "groundskeeping", "gala-bau", "baumpflege"),
    ("wartung", "Wartung", "facility", "instandhaltung", "instandsetzung", "maintenance", "reparatur", "repair", "wartungsplanung", "prüffristen", "vorbeugende instandhaltung", "tpm"),
    ("waescherei", "Wäscherei", "facility", "textilreinigung", "laundry", "mangeln", "chemische reinigung"),
    # --- textile, crafts, beauty ---------------------------------------------------------------------
    ("naeharbeiten", "Näharbeiten", "textile", "nähen", "nähmaschine", "sewing", "schneiderei", "änderungsschneiderei", "overlock", "sticken"),
    ("zuschnitt", "Zuschnitt", "textile", "schnittmuster", "pattern making", "gradieren", "maßanfertigung", "modellentwicklung"),
    ("textilverarbeitung", "Textilverarbeitung", "textile", "textiltechnik", "stoffkunde", "konfektion", "polsterei", "raumausstattung"),
    ("friseur", "Friseurhandwerk", "beauty", "friseur", "haarschnitt", "coloration", "färben", "hairdressing", "styling", "hochsteckfrisuren", "colorationen", "strähnentechnik"),
    ("kosmetik", "Kosmetik", "beauty", "kosmetikerin", "gesichtsbehandlung", "maniküre", "pediküre", "wimpernverlängerung", "make-up", "beauty treatment"),
    ("massage_beauty", "Wellness", "beauty", "spa", "wellnessanwendungen", "sauna"),
    ("tattoo", "Tätowieren", "beauty", "piercing", "permanent make-up"),
    ("goldschmied", "Goldschmiedearbeiten", "textile", "schmuckherstellung", "gravur", "uhrmacher", "feinmechanik"),
    ("floristik", "Floristik", "textile", "blumenbinderei", "gestecke", "floristry"),
    # --- agriculture, environment, animals --------------------------------------------------------------
    ("landwirtschaft", "Landwirtschaft", "agriculture", "agriculture", "ackerbau", "ernte", "aussaat", "landwirt", "farming"),
    ("landmaschinen", "Landmaschinen", "agriculture", "traktor", "mähdrescher", "landtechnik", "schlepper"),
    ("tierhaltung", "Tierhaltung", "agriculture", "nutztierhaltung", "melken", "tierpflege", "animal care", "zucht", "stallarbeit"),
    ("pflanzenschutz", "Pflanzenschutz", "agriculture", "düngung", "sachkundenachweis pflanzenschutz", "pflanzenbau", "gartenbau", "gärtner"),
    ("forst", "Forstwirtschaft", "agriculture", "waldarbeit", "motorsägenschein", "holzernte", "forestry"),
    ("umweltschutz", "Umweltschutz", "science", "nachhaltigkeit", "sustainability", "umweltmanagement", "iso 14001", "esg", "co2-bilanz", "energiemanagement"),
    # --- science and research -----------------------------------------------------------------------------
    ("forschung", "Forschung", "science", "research", "wissenschaftliches arbeiten", "publikationen", "studiendesign", "versuchsplanung", "drittmittel"),
    ("chemie", "Chemie", "science", "chemistry", "synthese", "hplc", "gc-ms", "spektroskopie", "titration", "chemielaborant"),
    ("biologie", "Biologie", "science", "biology", "mikrobiologie", "molekularbiologie", "pcr", "zellkultur", "biotechnologie"),
    ("physik", "Physik", "science", "physics", "optik", "lasertechnik", "vakuumtechnik", "messreihen", "technische optik"),
    ("pharma", "Pharmazeutische Industrie", "science", "gmp", "gxp", "validierung", "qualifizierung", "regulatory affairs", "pharmakovigilanz"),
    # --- security and safety ---------------------------------------------------------------------------------
    ("sachkunde34a", "Sachkundeprüfung §34a", "security", "sachkundeprüfung", "34a", "unterrichtung nach 34a", "bewachungsgewerbe"),
    ("objektschutz", "Objektschutz", "security", "werkschutz", "sicherheitsdienst", "security service", "revierdienst", "empfangsdienst", "veranstaltungsschutz", "doorman", "zutrittskontrolle"),
    ("brandschutz", "Brandschutz", "security", "brandschutzhelfer", "fire safety", "evakuierung", "brandmeldeanlage"),
    ("arbeitssicherheit", "Arbeitssicherheit", "security", "unfallverhütung", "occupational safety", "arbeitsschutz", "sicherheitsvorschriften", "sifa", "gefährdungsbeurteilung", "psa"),
    ("videoueberwachung", "Videoüberwachung", "security", "leitstelle", "zutrittskontrolle", "alarmanlagen", "cctv"),
    # --- production and quality ------------------------------------------------------------------------------
    ("produktion", "Produktion", "production", "fertigung", "serienfertigung", "manufacturing", "maschinenbedienung", "maschinenführer", "anlagenführer", "produktionsplanung", "schichtführer", "machine operation", "störungsbehebung"),
    ("qualitaetskontrolle", "Qualitätskontrolle", "production", "qualitätsprüfung", "quality control", "endkontrolle", "wareneingangsprüfung", "sichtprüfung", "prüfprotokolle", "quality inspection", "prüfprotokoll"),
    ("verpackung", "Verpackung", "production", "abfüllung", "etikettierung", "packaging", "konfektionierung"),
    ("ruestung", "Rüsten", "production", "maschineneinrichtung", "werkzeugwechsel", "störungsbeseitigung"),
    # --- HR, office, administration ---------------------------------------------------------------------------
    ("personalwesen", "Personalwesen", "hr", "personalverwaltung", "human resources", "recruiting", "bewerbermanagement", "hr", "personalbetreuung", "onboarding", "personalentwicklung", "zeitwirtschaft", "personalbeschaffung", "talent acquisition", "active sourcing", "stellenausschreibung", "vorstellungsgespräche", "mitarbeiterentwicklung", "talent management", "weiterbildungsplanung", "nachfolgeplanung", "mitarbeitergespräche", "zeiterfassung", "dienstplanung", "schichtplanung", "urlaubsplanung", "workforce management"),
    ("sachbearbeitung", "Sachbearbeitung", "office", "büroorganisation", "administration", "verwaltung", "office management", "korrespondenz", "schriftverkehr", "aktenführung", "datenerfassung", "sekretariat", "assistenz der geschäftsführung"),
    ("terminplanung", "Terminplanung", "office", "kalenderverwaltung", "scheduling", "reiseplanung", "reisekostenabrechnung", "veranstaltungsorganisation"),
    ("einkauf", "Einkauf", "office", "beschaffung", "procurement", "lieferantenmanagement", "purchasing", "bestellabwicklung", "preisverhandlungen"),
    ("projectmanagement", "Projektmanagement", "office", "project management", "projektleitung", "projektsteuerung", "meilensteinplanung", "ressourcenplanung", "budgetverantwortung"),
    ("training", "Schulungen", "business", "schulung", "training", "einweisung", "unterweisung", "workshops", "anwenderschulung"),
    ("support", "Anwendersupport", "business", "user support", "1st level", "2nd level", "first level", "second level", "anwenderbetreuung", "technischer support", "it-support"),
    ("digitalisierung", "Digitalisierung", "business", "prozessdigitalisierung", "digital transformation", "digitale transformation"),
    ("telefonzentrale", "Telefonzentrale", "office", "empfangstätigkeiten", "call center", "telefonische betreuung", "postbearbeitung"),
    ("immobilien", "Immobilien", "realestate", "makler", "real estate", "objektverwaltung", "hausverwaltung", "wohnungswirtschaft", "exposé", "mietverwaltung", "nebenkostenabrechnung", "wegverwaltung"),
    # --- sport and leisure -------------------------------------------------------------------------------------
    ("fitness", "Fitnesstraining", "sport", "trainingsplanung", "personal training", "gerätetraining", "kursleitung", "fitness", "trainerlizenz"),
    ("ernaehrungsberatung", "Ernährungsberatung", "sport", "ernährungswissenschaft", "nutrition", "diätetik", "diätassistenz"),
    ("schwimmen", "Rettungsschwimmen", "sport", "bademeister", "schwimmmeister", "dlrg", "aufsicht"),
    ("tourismus", "Tourismus", "sport", "reiseverkehr", "touristik", "reisebüro", "reiseleitung", "amadeus", "sabre"),
    # --- generic soft skills and conditions -----------------------------------------------------------------------
    ("teamfaehigkeit", "Teamfähigkeit", "soft", "teamarbeit", "teamwork", "teamplayer", "team player", "kooperationsfähigkeit"),
    ("zuverlaessigkeit", "Zuverlässigkeit", "soft", "zuverlässig", "reliability", "reliable", "pünktlichkeit", "verantwortungsbewusstsein"),
    ("sorgfalt", "Sorgfalt", "soft", "sorgfältig", "genauigkeit", "accuracy", "gewissenhaft", "detailgenauigkeit", "präzision", "liebe zum detail", "eye for detail", "attention to detail"),
    ("belastbarkeit", "Belastbarkeit", "soft", "belastbar", "resilience", "stressresistent", "körperliche belastbarkeit", "stressresistenz"),
    ("flexibilitaet", "Flexibilität", "soft", "flexibel", "flexibility", "anpassungsfähigkeit", "einsatzflexibilität"),
    ("kommunikationsfaehigkeit", "Kommunikationsfähigkeit", "soft", "kommunikationsstark", "communication skills", "ausdrucksfähigkeit", "verhandlungsgeschick", "überzeugungskraft"),
    ("selbststaendigkeit", "Selbstständige Arbeitsweise", "soft", "selbstständig", "eigenverantwortlich", "independent working", "eigeninitiative", "strukturierte arbeitsweise", "organisationsfähigkeit"),
    ("kundenorientierung", "Kundenorientierung", "soft", "serviceorientierung", "customer focus", "dienstleistungsorientiert", "freundliches auftreten"),
    ("empathie", "Empathie", "soft", "einfühlungsvermögen", "empathy", "wertschätzung"),
    ("geduld", "Geduld", "soft", "patience", "ausdauer", "gelassenheit"),
    ("lernbereitschaft", "Lernbereitschaft", "soft", "weiterbildungsbereitschaft", "willingness to learn", "wissbegierig", "neugier"),
    ("analytisch", "Analytisches Denken", "soft", "analytical thinking", "problemlösungskompetenz", "lösungsorientiert", "konzeptionelles denken", "logisches denken"),
    ("fuehrungserfahrung", "Führungserfahrung", "soft", "teamleitung", "mitarbeiterführung", "leadership", "disziplinarische verantwortung", "personalverantwortung"),
    ("interkulturell", "Interkulturelle Kompetenz", "soft", "intercultural", "internationale zusammenarbeit"),
    ("schichtbereitschaft", "Schichtbereitschaft", "condition", "schichtarbeit", "schichtdienst", "shift work", "wochenendarbeit", "nachtdienst", "rufbereitschaft", "bereitschaftsdienst", "wechselschicht"),
    ("reisebereitschaft", "Reisebereitschaft", "condition", "montagebereitschaft", "willingness to travel", "dienstreisen", "außendiensttätigkeit", "außendienst", "innendienst"),
    ("koerperlichearbeit", "Körperliche Arbeit", "condition", "körperlich anspruchsvoll", "physical work", "heben und tragen", "stehende tätigkeit"),
    ("erscheinungsbild", "Gepflegtes Erscheinungsbild", "condition", "gepflegtes auftreten", "professional appearance", "sicheres auftreten"),
    ("polizeiliches", "Polizeiliches Führungszeugnis", "condition", "führungszeugnis", "einwandfreies führungszeugnis", "background check", "erweitertes führungszeugnis"),
    ("gesundheitszeugnis", "Gesundheitszeugnis", "condition", "belehrung nach infektionsschutzgesetz", "infektionsschutzgesetz", "arbeitsmedizinische vorsorge", "g25", "g41"),
    ("impfschutz", "Impfschutz", "condition", "masernschutz", "impfnachweis", "vaccination"),
    ("homeoffice_ready", "Homeoffice", "condition", "remote work", "mobiles arbeiten", "hybrides arbeiten"),

    # --- widened coverage: trades whose whole field was one or two rows --
    ("grundpflege", "Grundpflege", "care", "körperpflege", "waschen und kleiden", "basic care", "prophylaxen", "mobilisation"),
    ("behandlungspflege", "Behandlungspflege", "care", "medikamentengabe", "verbandwechsel", "injektionen", "blutentnahme", "katheterversorgung", "stomaversorgung"),
    ("palliativpflege", "Palliativpflege", "care", "palliative care", "sterbebegleitung", "hospiz", "schmerzmanagement"),
    ("gerontopsychiatrie", "Gerontopsychiatrie", "care", "demenzbetreuung", "demenz", "validation", "gerontopsychiatrische betreuung"),
    ("intensivpflege", "Intensivpflege", "care", "intensivstation", "beatmung", "icu", "anästhesiepflege"),
    ("pflegegrad", "Pflegegrad-Einstufung", "care", "begutachtung", "mdk", "medizinischer dienst", "pflegegutachten", "sgb xi"),
    ("kinderkrankenpflege", "Kinderkrankenpflege", "care", "pädiatrie", "neonatologie", "paediatric nursing", "säuglingspflege"),
    ("op_pflege", "OP-Pflege", "health", "operationsdienst", "instrumentieren", "springerdienst", "sterilgutversorgung", "aseptik"),
    ("laborassistenz", "Laborassistenz", "health", "labordiagnostik", "probenaufbereitung", "mta-l", "hämatologie", "klinische chemie"),
    ("fruehfoerderung", "Frühförderung", "social", "heilpädagogik", "entwicklungsförderung", "early intervention"),
    ("kinderbetreuung", "Kinderbetreuung", "education", "erzieherin", "kita", "kindergarten", "childcare", "krippe", "hort", "pädagogische fachkraft"),
    ("erwachsenenbildung", "Erwachsenenbildung", "education", "weiterbildung", "dozent", "adult education", "seminarleitung", "ada-schein"),
    ("ausbildereignung", "Ausbildereignung", "education", "ausbilder", "aevo", "azubi-betreuung", "lehrlingsausbildung"),
    ("personaladministration", "Personaladministration", "hr", "personalakte", "zeugniserstellung", "vertragswesen", "hr administration", "on- und offboarding"),
    ("kunststofftechnik", "Kunststofftechnik", "production", "spritzguss", "extrusion", "thermoformen", "injection moulding"),
    ("lebensmittelproduktion", "Lebensmittelproduktion", "production", "lebensmitteltechnik", "abfüllung", "food production", "hygieneschulung", "ifs standard"),
    ("kfz_mechatronik", "Kfz-Mechatronik", "automotive", "kfz-mechaniker", "fahrzeugtechnik", "motorinstandsetzung", "fehlerdiagnose", "automotive repair", "hu-vorbereitung"),
    ("nutzfahrzeuge", "Nutzfahrzeuge", "automotive", "lkw-werkstatt", "landmaschinentechnik", "baumaschinen", "commercial vehicles"),
    ("luftfahrttechnik", "Luftfahrttechnik", "aviation", "fluggerätmechaniker", "line maintenance", "part-145", "easa", "luftfahrzeugtechnik"),
    ("flugbegleitung", "Flugbegleitung", "aviation", "kabinenpersonal", "cabin crew", "flugbegleiter", "safety and emergency procedures"),
    ("bodenabfertigung", "Bodenabfertigung", "aviation", "ground handling", "gepäckabfertigung", "vorfelddienst", "luftsicherheit"),
    ("kassiertaetigkeit", "Kassentätigkeit", "retail", "kassieren", "kassensystem", "tagesabschluss", "geldzählung"),
    ("hotelrezeption", "Hotelrezeption", "hospitality", "front office", "check-in und check-out", "reservierungen", "opera pms", "gästeempfang"),
    ("hauswirtschaft", "Hauswirtschaft", "hospitality", "housekeeping", "zimmerreinigung", "wäschepflege", "hauswirtschafterin"),
    ("immobilienverwaltung", "Immobilienverwaltung", "realestate", "hausverwaltung", "weg-verwaltung", "mietverwaltung", "property management", "nebenkostenabrechnung"),
    ("immobilienvermittlung", "Immobilienvermittlung", "realestate", "makler", "objektbesichtigung", "exposé", "real estate agent", "wertermittlung"),
    ("facility_technik", "Technisches Facility Management", "facility", "haustechnik", "hausmeisterdienste", "gebäudetechnik", "störungsdienst", "kleinreparaturen"),
    ("buergerservice", "Bürgerservice", "public", "einwohnermeldeamt", "meldewesen", "ausweisdokumente", "publikumsverkehr", "citizen services"),
    ("sozialleistungen", "Sozialleistungen", "public", "sgb ii", "bürgergeld", "wohngeld", "leistungsgewährung", "antragsbearbeitung"),
    ("veranstaltungssicherheit", "Veranstaltungssicherheit", "security", "eventsicherheit", "einlasskontrolle", "crowd management", "ordnungsdienst"),
    ("digitalberatung", "Digitalberatung", "consulting", "digitale transformation", "digitalisierungsstrategie", "digital consulting", "it-strategie"),
    ("ausschreibungsmanagement", "Ausschreibungsmanagement", "consulting", "angebotserstellung", "bid management", "kalkulation angebot"),
)


# --------------------------------------------------------------------------
# Fields that had no row at all
# --------------------------------------------------------------------------

FURTHER_FIELD_SKILLS: tuple[tuple[str, ...], ...] = (
    # --- therapy and the allied health professions ----------------------------
    ("physiotherapie", "Physiotherapie", "therapy", "krankengymnastik", "manuelle therapie", "physiotherapist", "bobath", "lymphdrainage", "physio"),
    ("ergotherapie", "Ergotherapie", "therapy", "occupational therapy", "handtherapie", "sensorische integration", "ergotherapeut"),
    ("logopaedie", "Logopädie", "therapy", "sprachtherapie", "speech therapy", "stimmtherapie", "aphasie", "logopäde", "myofunktionelle therapie"),
    ("podologie", "Podologie", "therapy", "fusspflege", "medizinische fusspflege", "podiatry", "podologe"),
    ("psychotherapie", "Psychotherapie", "therapy", "verhaltenstherapie", "gesprächstherapie", "psychotherapeut", "traumatherapie", "psychologische beratung"),
    ("massage_therapie", "Massagetherapie", "therapy", "masseur", "medizinische bademeister", "manuelle lymphdrainage"),
    ("rehabilitation", "Rehabilitation", "therapy", "reha", "anschlussheilbehandlung", "rehabilitationssport", "wiedereingliederung"),
    # --- eyes, ears, teeth, prosthetics ---------------------------------------
    ("augenoptik", "Augenoptik", "health", "optiker", "refraktion", "brillenanpassung", "optometrie", "kontaktlinsenanpassung", "optician"),
    ("hoerakustik", "Hörakustik", "health", "hörgeräteakustiker", "audiometrie", "hearing aid", "otoplastik"),
    ("zahntechnik", "Zahntechnik", "health", "zahntechniker", "dental lab", "kronen und brücken", "prothetik labor", "zahnersatz"),
    ("orthopaedietechnik", "Orthopädietechnik", "health", "orthopädiemechanik", "prothesenbau", "orthesen", "einlagenversorgung", "prosthetics"),
    ("zahnmedizinische_assistenz", "Zahnmedizinische Assistenz", "health", "zfa", "zahnarzthelferin", "stuhlassistenz", "prophylaxe", "dental assistant"),
    ("pta", "Pharmazeutisch-technische Assistenz", "health", "pta", "apothekenhelferin", "rezeptur", "arzneimittelabgabe", "pharmacy technician"),
    # --- rescue, fire, enforcement --------------------------------------------
    ("rettungsdienst", "Rettungsdienst", "emergency", "notfallsanitäter", "rettungssanitäter", "rettungsassistent", "paramedic", "krankentransport", "notarztbegleitung"),
    ("feuerwehr", "Feuerwehr", "emergency", "brandbekämpfung", "atemschutz", "firefighting", "löscheinsatz", "technische hilfeleistung"),
    ("katastrophenschutz", "Katastrophenschutz", "emergency", "bevölkerungsschutz", "civil protection", "einsatzleitung", "gefahrenabwehr"),
    ("justizvollzug", "Justizvollzug", "public", "vollzugsdienst", "strafvollzug", "jva", "corrections"),
    # --- wood, glass, metal shaping -------------------------------------------
    ("tischlerei", "Tischlerei", "trade", "schreiner", "holzbearbeitung", "möbelbau", "carpentry", "furnierarbeiten", "kantenanleimer"),
    ("zimmerei", "Zimmerei", "construction", "zimmerer", "holzbau", "dachstuhl", "abbund", "timber framing"),
    ("glaserei", "Glaserei", "trade", "glaser", "verglasung", "isolierglas", "glazing", "fensterbau"),
    ("werkzeugbau", "Werkzeugbau", "trade", "formenbau", "vorrichtungsbau", "tool making", "lehrenbau"),
    ("metallbau", "Metallbau", "trade", "schlosser", "stahlbau", "konstruktionsmechanik", "metalworking", "geländerbau"),
    ("oberflaechentechnik", "Oberflächentechnik", "production", "galvanik", "pulverbeschichtung", "eloxieren", "surface treatment", "strahlen"),
    ("zfp", "Zerstörungsfreie Prüfung", "production", "ultraschallprüfung", "röntgenprüfung", "magnetpulverprüfung", "non-destructive testing", "eindringprüfung"),
    # --- building services and energy ------------------------------------------
    ("kaeltetechnik", "Kältetechnik", "trade", "klimatechnik", "kälteanlagenbauer", "refrigeration", "wärmepumpen", "lüftungstechnik"),
    ("gebaeudeautomation", "Gebäudeautomation", "trade", "msr-technik", "building automation", "gebäudeleittechnik", "knx", "regelungstechnik"),
    ("aufzugstechnik", "Aufzugstechnik", "trade", "aufzugsmonteur", "fahrtreppen", "lift maintenance", "aufzugsprüfung"),
    ("photovoltaik", "Photovoltaik", "energy", "solaranlagen", "pv-montage", "solar", "wechselrichter", "solarteur"),
    ("windkraft", "Windkraft", "energy", "windenergieanlagen", "wind turbine", "rotorblattinspektion", "offshore wind"),
    ("netztechnik", "Netztechnik", "energy", "stromnetz", "netzbetrieb", "umspannwerk", "grid operations", "kabelmontage", "freileitung"),
    ("energieberatung", "Energieberatung", "energy", "energieausweis", "energieeffizienz", "energy consulting", "gebäudeenergieberatung", "geg"),
    # --- water, waste, environment ---------------------------------------------
    ("wassertechnik", "Wasser- und Abwassertechnik", "environment", "kläranlage", "abwasserbehandlung", "water treatment", "trinkwasserversorgung", "kanalbetrieb"),
    ("abfallwirtschaft", "Abfallwirtschaft", "environment", "entsorgung", "recycling", "waste management", "wertstoffhof", "abfallrecht"),
    ("nachhaltigkeit", "Nachhaltigkeitsberichterstattung", "environment", "esg-reporting", "csrd", "sustainability reporting", "ökobilanz"),
    ("bergbau", "Bergbau", "environment", "tagebau", "mining", "sprengarbeiten", "gewinnungstechnik"),
    # --- surveying, geo, planning -----------------------------------------------
    ("vermessung", "Vermessung", "engineering", "geodäsie", "vermessungstechniker", "surveying", "tachymeter", "absteckung", "katastervermessung"),
    ("gis_geo", "Geoinformationssysteme", "engineering", "arcgis", "qgis", "geodatenverarbeitung", "geoinformatik", "kartografie"),
    # --- culture, media, knowledge ----------------------------------------------
    ("bibliothek", "Bibliothekswesen", "culture", "bibliothekar", "mediothek", "katalogisierung", "library science"),
    ("archiv", "Archivwesen", "culture", "archivar", "records management", "schriftgutverwaltung", "digitalisierung von beständen"),
    ("museum", "Museumsarbeit", "culture", "kuratieren", "ausstellungsgestaltung", "museum", "sammlungspflege", "restaurierung"),
    ("musik", "Musikausübung", "culture", "instrumentalunterricht", "orchester", "chorleitung", "music teaching", "korrepetition"),
    ("gebaerdensprache", "Gebärdensprache", "media", "dgs", "sign language", "gebärdensprachdolmetschen"),
    # --- transport and delivery --------------------------------------------------
    ("busfahren", "Busfahren", "logistics", "linienverkehr", "omnibus", "bus driver", "reisebus"),
    ("kurierdienst", "Kurier- und Paketdienst", "logistics", "paketzustellung", "zustellung", "courier", "auslieferungsfahrer", "letzte meile"),
    ("fahrschule", "Fahrschulausbildung", "education", "fahrlehrer", "driving instructor", "fahrschulunterricht"),
    ("hafenlogistik", "logistics", "seehafen", "containerumschlag", "port operations", "terminalbetrieb"),
    ("luftfracht", "Luftfracht", "logistics", "air cargo", "frachtabfertigung", "awb", "luftfrachtsicherheit"),
    # --- food and drink production ------------------------------------------------
    ("brauerei", "Brauerei- und Getränketechnik", "production", "brauer", "mälzer", "getränkeherstellung", "brewing", "abfüllanlage"),
    ("molkerei", "Molkereitechnik", "production", "milchwirtschaft", "käserei", "dairy", "milchtechnologe"),
    ("fleischverarbeitung", "Fleischverarbeitung", "production", "fleischer", "metzger", "zerlegung", "wurstherstellung", "butchery"),
    # --- regulated production ------------------------------------------------------
    ("gmp", "GMP-Produktion", "production", "good manufacturing practice", "chargendokumentation", "pharmaproduktion", "validierung reinraum"),
    ("reinraum", "Reinraumtechnik", "production", "cleanroom", "reinraumklasse", "partikelmessung", "reinraumbekleidung"),
    ("medizinprodukte", "Medizinprodukte", "production", "mdr", "iso 13485", "medical devices", "medizinproduktebeauftragter"),
    ("klinische_studien", "Klinische Studien", "science", "clinical trials", "studienassistenz", "monitoring studien", "prüfarzt"),
    ("arbeitsvorbereitung", "Arbeitsvorbereitung", "production", "fertigungsplanung", "arbeitspläne", "production planning", "reihenfolgeplanung"),
    # --- money and law, the gaps ----------------------------------------------------
    ("wirtschaftspruefung", "Wirtschaftsprüfung", "finance", "jahresabschlussprüfung", "audit", "prüfungsassistenz", "ifrs-prüfung"),
    ("aktuariat", "Aktuariat", "insurance", "versicherungsmathematik", "actuarial", "tarifkalkulation", "rückstellungsberechnung"),
    ("betriebsrat", "Betriebsverfassungsrecht", "hr", "mitbestimmung", "works council", "betriebsvereinbarungen"),
    # --- social work, the gaps --------------------------------------------------------
    ("suchthilfe", "Suchthilfe", "social", "suchtberatung", "drogenhilfe", "addiction counselling", "substitution"),
    ("migrationsberatung", "Migrationsberatung", "social", "integrationsarbeit", "asylverfahrensberatung", "migration counselling", "sprachmittlung"),
    ("streetwork", "Aufsuchende Sozialarbeit", "social", "streetwork", "gemeinwesenarbeit", "outreach work", "quartiersarbeit"),
    ("schulbegleitung", "Schulbegleitung", "social", "integrationshilfe", "schulassistenz", "one-to-one support"),
    ("betreutes_wohnen", "Betreutes Wohnen", "social", "wohngruppe", "assisted living", "ambulant betreutes wohnen"),
    # --- tourism and leisure ------------------------------------------------------------
    # --- quality and audit ----------------------------------------------------------------
    ("auditierung", "Auditierung", "quality", "internes audit", "lieferantenaudit", "auditor", "iso 9001 audit"),
)


# --------------------------------------------------------------------------
# The same skills, in the other languages the app reads
# --------------------------------------------------------------------------

LOCALISED_ALIASES: dict[str, tuple[tuple[str, ...], ...]] = {
    # Each row is (skill id, *aliases). They are merged into that skill's own
    # aliases, so a skill reached by one of these is reported under the label
    # it already has.
    #
    # The gazetteer was written from German adverts and grew English aliases
    # because German adverts are full of English. The other five languages
    # had almost none, which is why a Spanish advert for a waiter and a Dutch
    # one for a service engineer came back with no known skills at all --
    # every requirement in them had to be guessed, and guessing is the part
    # that produces noise. This is the half of "works in seven languages"
    # that was missing.
    #
    # Only the occupations where a non-German advert is likely: the trades,
    # care, hospitality, logistics, retail, office work and the soft skills
    # every advert closes with. Technology names are international already.
    "uk": (
        ("pflege", "догляд", "сестринський догляд", "медсестра", "медичний брат", "патронаж"),
        ("grundpflege", "гігієнічний догляд", "базовий догляд"),
        ("behandlungspflege", "лікувальні процедури", "перев'язки", "ін'єкції", "забір крові"),
        ("betreuung", "супровід", "соціальний супровід", "опіка"),
        ("erstehilfe", "перша допомога", "долікарська допомога"),
        ("hygiene", "санітарні норми", "дезінфекція", "санітарія"),
        ("physiotherapie", "фізіотерапія", "лікувальна фізкультура", "реабілітолог"),
        ("apotheke", "фармація", "фармацевт", "аптека"),
        ("kueche", "кухня", "приготування страв", "кухар", "гарячий цех", "пароконвектомат"),
        ("service_gastro", "обслуговування гостей", "офіціант", "зал ресторану"),
        ("barista", "бариста", "бармен", "приготування кави"),
        ("haccp", "хассп", "безпечність харчових продуктів"),
        ("baeckerei", "пекарня", "кондитерська", "випічка", "пекар"),
        ("reinigung", "прибирання", "клінінг", "прибиральниця", "вологе прибирання"),
        ("waescherei", "пральня", "хімчистка"),
        ("hausmeister", "технічне обслуговування будівлі", "завгосп", "дрібний ремонт"),
        ("wartung", "технічне обслуговування", "ремонт обладнання", "профілактика обладнання"),
        ("lager", "склад", "складський облік", "комірник"),
        ("stapler", "навантажувач", "автонавантажувач", "штабелер"),
        ("kommissionierung", "комплектація замовлень", "збірка замовлень", "пікінг"),
        ("disposition", "диспетчеризація", "логістика перевезень", "маршрутизація"),
        ("ladungssicherung", "кріплення вантажу", "розміщення вантажу"),
        ("kasse", "каса", "касове обслуговування", "робота на касі"),
        ("verkauf", "продажі", "продавець", "торгівля"),
        ("kundenberatung", "консультування клієнтів", "обслуговування клієнтів"),
        ("inventur", "інвентаризація", "переоблік"),
        ("maurer", "мулярні роботи", "кладка", "муляр"),
        ("maler", "малярні роботи", "фарбування", "штукатурка", "маляр"),
        ("fliesen", "плиткові роботи", "укладання плитки", "плиточник"),
        ("elektroinstallation", "електромонтаж", "електрика", "електрик"),
        ("sanitaer", "сантехніка", "водопровід", "сантехнік"),
        ("schweissen", "зварювання", "зварювальні роботи", "зварник"),
        ("montage", "монтаж", "складання конструкцій", "монтажник"),
        ("tischlerei", "столярні роботи", "деревообробка", "столяр"),
        ("metallbau", "металоконструкції", "слюсарні роботи", "слюсар"),
        ("kfz_mechatronik", "ремонт автомобілів", "автомеханік", "діагностика авто"),
        ("hydraulik", "гідравліка", "пневматика"),
        ("buchhaltung", "бухгалтерія", "бухгалтерський облік", "бухгалтер"),
        ("sachbearbeitung", "діловодство", "обробка документів"),
        ("einkauf", "закупівлі", "постачання"),
        ("kinderbetreuung", "догляд за дітьми", "вихователь", "дитячий садок"),
        ("paedagogik", "педагогіка", "виховна робота"),
        ("sozialarbeit", "соціальна робота", "соціальний працівник"),
        ("unterricht", "викладання", "проведення занять", "вчитель"),
        ("objektschutz", "охорона об'єктів", "охоронець", "контроль доступу"),
        ("arbeitssicherheit", "охорона праці", "техніка безпеки"),
        ("landwirtschaft", "сільське господарство", "рослинництво", "збір урожаю"),
        ("tierhaltung", "тваринництво", "догляд за тваринами"),
        ("produktion", "виробництво", "виробнича лінія", "оператор лінії"),
        ("qualitaetskontrolle", "контроль якості", "перевірка якості"),
        ("verpackung", "пакування", "фасування"),
        ("lebensmittelproduktion", "харчове виробництво", "переробка продуктів"),
        ("fotografie", "фотозйомка", "фотограф", "обробка фото"),
        ("videoproduktion", "відеозйомка", "монтаж відео"),
        ("grafikdesign", "графічний дизайн", "верстка", "макети"),
        ("teamfaehigkeit", "робота в команді", "командна робота"),
        ("zuverlaessigkeit", "надійність", "відповідальність"),
        ("kommunikationsfaehigkeit", "комунікабельність", "навички спілкування"),
        ("kundenorientierung", "орієнтація на клієнта", "клієнтоорієнтованість"),
        ("belastbarkeit", "стресостійкість", "витривалість"),
        ("selbststaendigkeit", "самостійність", "уміння працювати самостійно"),
        ("flexibilitaet", "гнучкість", "адаптивність"),
        ("sorgfalt", "уважність до деталей", "акуратність"),
        ("lernbereitschaft", "готовність навчатися", "швидке навчання"),
        ("fuehrungserfahrung", "керівний досвід", "управління командою"),
        ("schichtbereitschaft", "змінний графік", "готовність до змін", "нічні зміни"),
        ("koerperlichearbeit", "фізична робота", "фізичні навантаження"),
        ("reisebereitschaft", "готовність до відряджень", "роз'їзний характер роботи"),
    ),
    "ru": (
        ("pflege", "уход", "сестринский уход", "медсестра", "патронаж"),
        ("grundpflege", "гигиенический уход", "базовый уход"),
        ("behandlungspflege", "лечебные процедуры", "перевязки", "инъекции", "забор крови"),
        ("betreuung", "сопровождение", "социальное сопровождение", "опека"),
        ("erstehilfe", "первая помощь", "доврачебная помощь"),
        ("hygiene", "санитарные нормы", "дезинфекция", "санитария"),
        ("physiotherapie", "физиотерапия", "лечебная физкультура", "реабилитолог"),
        ("apotheke", "фармация", "фармацевт", "аптека"),
        ("kueche", "кухня", "приготовление блюд", "повар", "горячий цех", "пароконвектомат"),
        ("service_gastro", "обслуживание гостей", "официант", "зал ресторана"),
        ("barista", "бариста", "бармен", "приготовление кофе"),
        ("haccp", "хассп", "безопасность пищевых продуктов"),
        ("baeckerei", "пекарня", "кондитерская", "выпечка", "пекарь"),
        ("reinigung", "уборка", "клининг", "уборщица", "влажная уборка"),
        ("waescherei", "прачечная", "химчистка"),
        ("hausmeister", "техническое обслуживание здания", "мелкий ремонт"),
        ("wartung", "техническое обслуживание", "ремонт оборудования"),
        ("lager", "склад", "складской учет", "кладовщик"),
        ("stapler", "погрузчик", "автопогрузчик", "штабелер"),
        ("kommissionierung", "комплектация заказов", "сборка заказов", "пикинг"),
        ("disposition", "диспетчеризация", "логистика перевозок", "маршрутизация"),
        ("ladungssicherung", "крепление груза", "размещение груза"),
        ("kasse", "касса", "кассовое обслуживание", "работа на кассе"),
        ("verkauf", "продажи", "продавец", "торговля"),
        ("kundenberatung", "консультирование клиентов", "обслуживание клиентов"),
        ("inventur", "инвентаризация", "переучет"),
        ("maurer", "кладка", "каменные работы", "каменщик"),
        ("maler", "малярные работы", "покраска", "штукатурка", "маляр"),
        ("fliesen", "укладка плитки", "плиточные работы", "плиточник"),
        ("elektroinstallation", "электромонтаж", "электрика", "электрик"),
        ("sanitaer", "сантехника", "водопровод", "сантехник"),
        ("schweissen", "сварка", "сварочные работы", "сварщик"),
        ("montage", "монтаж", "сборка конструкций", "монтажник"),
        ("tischlerei", "столярные работы", "деревообработка", "столяр"),
        ("metallbau", "металлоконструкции", "слесарные работы", "слесарь"),
        ("kfz_mechatronik", "ремонт автомобилей", "автомеханик", "диагностика авто"),
        ("hydraulik", "гидравлика", "пневматика"),
        ("buchhaltung", "бухгалтерия", "бухгалтерский учет", "бухгалтер"),
        ("sachbearbeitung", "делопроизводство", "обработка документов"),
        ("einkauf", "закупки", "снабжение"),
        ("kinderbetreuung", "уход за детьми", "воспитатель", "детский сад"),
        ("paedagogik", "педагогика", "воспитательная работа"),
        ("sozialarbeit", "социальная работа", "социальный работник"),
        ("unterricht", "преподавание", "проведение занятий", "учитель"),
        ("objektschutz", "охрана объектов", "охранник", "контроль доступа"),
        ("arbeitssicherheit", "охрана труда", "техника безопасности"),
        ("landwirtschaft", "сельское хозяйство", "растениеводство", "сбор урожая"),
        ("tierhaltung", "животноводство", "уход за животными"),
        ("produktion", "производство", "производственная линия", "оператор линии"),
        ("qualitaetskontrolle", "контроль качества", "проверка качества"),
        ("verpackung", "упаковка", "фасовка"),
        ("lebensmittelproduktion", "пищевое производство", "переработка продуктов"),
        ("fotografie", "фотосъемка", "фотограф", "обработка фото"),
        ("videoproduktion", "видеосъемка", "монтаж видео"),
        ("grafikdesign", "графический дизайн", "верстка", "макеты"),
        ("teamfaehigkeit", "работа в команде", "командная работа"),
        ("zuverlaessigkeit", "надежность", "ответственность"),
        ("kommunikationsfaehigkeit", "коммуникабельность", "навыки общения"),
        ("kundenorientierung", "ориентация на клиента", "клиентоориентированность"),
        ("belastbarkeit", "стрессоустойчивость", "выносливость"),
        ("selbststaendigkeit", "самостоятельность", "умение работать самостоятельно"),
        ("flexibilitaet", "гибкость", "адаптивность"),
        ("sorgfalt", "внимательность к деталям", "аккуратность"),
        ("lernbereitschaft", "готовность обучаться", "быстрая обучаемость"),
        ("fuehrungserfahrung", "руководящий опыт", "управление командой"),
        ("schichtbereitschaft", "сменный график", "готовность к сменам", "ночные смены"),
        ("koerperlichearbeit", "физическая работа", "физические нагрузки"),
        ("reisebereitschaft", "готовность к командировкам", "разъездной характер работы"),
    ),
    "es": (
        ("pflege", "cuidados", "enfermeria", "auxiliar de enfermeria", "cuidado de pacientes"),
        ("betreuung", "acompanamiento", "atencion a personas", "cuidado de mayores"),
        ("erstehilfe", "primeros auxilios"),
        ("hygiene", "higiene", "desinfeccion", "normas higienicas"),
        ("physiotherapie", "fisioterapia", "rehabilitacion fisica"),
        ("apotheke", "farmacia", "auxiliar de farmacia"),
        ("kueche", "cocina", "elaboracion de platos", "cocinero", "partida de cocina"),
        ("service_gastro", "atencion en sala", "camarero", "servicio de sala", "toma de comandas"),
        ("barista", "barista", "cocteleria", "barra", "camarero de barra"),
        ("haccp", "appcc", "seguridad alimentaria", "manipulador de alimentos"),
        ("baeckerei", "panaderia", "pasteleria", "obrador"),
        ("reinigung", "limpieza", "limpieza de oficinas", "personal de limpieza"),
        ("waescherei", "lavanderia", "tintoreria"),
        ("hausmeister", "mantenimiento de edificios", "conserje"),
        ("wartung", "mantenimiento", "reparacion de equipos", "mantenimiento preventivo"),
        ("lager", "almacen", "gestion de almacen", "mozo de almacen"),
        ("stapler", "carretilla elevadora", "carretillero", "toro"),
        ("kommissionierung", "preparacion de pedidos", "picking"),
        ("disposition", "planificacion de rutas", "gestion de transporte"),
        ("kasse", "caja", "cobro en caja", "tpv", "cajero"),
        ("verkauf", "ventas", "dependiente", "vendedor"),
        ("kundenberatung", "atencion al cliente", "asesoramiento al cliente"),
        ("inventur", "inventario", "recuento de stock"),
        ("maurer", "albanileria", "albanil"),
        ("maler", "pintura", "pintor", "revestimientos"),
        ("fliesen", "alicatado", "solado", "colocacion de azulejos"),
        ("elektroinstallation", "instalaciones electricas", "electricista"),
        ("sanitaer", "fontaneria", "fontanero", "climatizacion"),
        ("schweissen", "soldadura", "soldador", "soldadura tig"),
        ("montage", "montaje industrial", "ensamblaje", "instalacion de equipos"),
        ("tischlerei", "carpinteria", "carpintero", "ebanisteria"),
        ("metallbau", "cerrajeria", "estructuras metalicas", "calderero"),
        ("kfz_mechatronik", "mecanica de vehiculos", "mecanico", "diagnosis de averias"),
        ("buchhaltung", "contabilidad", "contable", "asientos contables"),
        ("sachbearbeitung", "gestion administrativa", "administrativo", "tramitacion de expedientes"),
        ("einkauf", "compras", "aprovisionamiento"),
        ("kinderbetreuung", "educacion infantil", "cuidado de ninos", "escuela infantil"),
        ("paedagogik", "pedagogia", "trabajo educativo"),
        ("sozialarbeit", "trabajo social", "trabajador social"),
        ("unterricht", "docencia", "impartir clases", "profesor"),
        ("objektschutz", "vigilancia de seguridad", "vigilante", "control de accesos"),
        ("arbeitssicherheit", "prevencion de riesgos laborales", "seguridad laboral", "prl"),
        ("landwirtschaft", "agricultura", "recoleccion", "labores agricolas"),
        ("tierhaltung", "ganaderia", "cuidado de animales"),
        ("produktion", "produccion", "linea de produccion", "operario de produccion"),
        ("qualitaetskontrolle", "control de calidad", "inspeccion de calidad"),
        ("verpackung", "envasado", "empaquetado"),
        ("lebensmittelproduktion", "industria alimentaria", "procesado de alimentos"),
        ("fotografie", "fotografia", "retoque fotografico"),
        ("grafikdesign", "diseno grafico", "maquetacion"),
        ("teamfaehigkeit", "trabajo en equipo"),
        ("zuverlaessigkeit", "fiabilidad", "responsabilidad"),
        ("kommunikationsfaehigkeit", "habilidades comunicativas", "don de gentes"),
        ("kundenorientierung", "orientacion al cliente", "vocacion de servicio"),
        ("belastbarkeit", "resistencia al estres", "tolerancia a la presion"),
        ("selbststaendigkeit", "autonomia", "capacidad de trabajar solo"),
        ("flexibilitaet", "flexibilidad", "adaptabilidad"),
        ("sorgfalt", "atencion al detalle", "meticulosidad"),
        ("lernbereitschaft", "ganas de aprender", "capacidad de aprendizaje"),
        ("fuehrungserfahrung", "experiencia liderando equipos", "gestion de equipos"),
        ("schichtbereitschaft", "disponibilidad para turnos", "turnos rotativos", "trabajo en fin de semana"),
        ("koerperlichearbeit", "trabajo fisico", "carga fisica"),
        ("reisebereitschaft", "disponibilidad para viajar"),
    ),
    "fr": (
        ("pflege", "soins", "aide-soignant", "soins infirmiers"),
        ("betreuung", "accompagnement", "aide a la personne"),
        ("erstehilfe", "premiers secours", "sst"),
        ("hygiene", "hygiene", "desinfection", "regles d'hygiene"),
        ("physiotherapie", "kinesitherapie", "reeducation"),
        ("apotheke", "pharmacie", "preparateur en pharmacie"),
        ("kueche", "cuisine", "preparation des plats", "cuisinier", "commis de cuisine"),
        ("service_gastro", "service en salle", "serveur", "prise de commandes"),
        ("barista", "barman", "cocktails", "service au bar"),
        ("haccp", "haccp", "securite alimentaire", "hygiene alimentaire"),
        ("baeckerei", "boulangerie", "patisserie", "boulanger"),
        ("reinigung", "nettoyage", "agent d'entretien", "entretien des locaux"),
        ("waescherei", "blanchisserie", "pressing"),
        ("hausmeister", "gardiennage d'immeuble", "petits travaux"),
        ("wartung", "maintenance", "entretien des equipements", "maintenance preventive"),
        ("lager", "entrepot", "magasinier", "gestion de stock"),
        ("stapler", "chariot elevateur", "cariste", "caces"),
        ("kommissionierung", "preparation de commandes", "picking"),
        ("disposition", "planification des tournees", "exploitation transport"),
        ("kasse", "caisse", "encaissement", "tenue de caisse"),
        ("verkauf", "vente", "vendeur", "conseiller de vente"),
        ("kundenberatung", "conseil client", "relation client"),
        ("inventur", "inventaire"),
        ("maurer", "maconnerie", "macon"),
        ("maler", "peinture en batiment", "peintre", "enduits"),
        ("fliesen", "carrelage", "carreleur"),
        ("elektroinstallation", "installation electrique", "electricien", "habilitation electrique"),
        ("sanitaer", "plomberie", "plombier", "chauffagiste"),
        ("schweissen", "soudure", "soudeur", "soudage tig"),
        ("montage", "montage industriel", "assemblage"),
        ("tischlerei", "menuiserie", "menuisier", "ebenisterie"),
        ("metallbau", "serrurerie", "chaudronnerie", "structures metalliques"),
        ("kfz_mechatronik", "mecanique automobile", "mecanicien", "diagnostic automobile"),
        ("buchhaltung", "comptabilite", "comptable", "saisie comptable"),
        ("sachbearbeitung", "gestion administrative", "traitement des dossiers"),
        ("einkauf", "achats", "approvisionnement"),
        ("kinderbetreuung", "petite enfance", "garde d'enfants", "auxiliaire de puericulture"),
        ("paedagogik", "pedagogie", "travail educatif"),
        ("sozialarbeit", "travail social", "assistant social"),
        ("unterricht", "enseignement", "animer des cours", "professeur"),
        ("objektschutz", "agent de securite", "surveillance de site", "controle d'acces"),
        ("arbeitssicherheit", "securite au travail", "prevention des risques"),
        ("landwirtschaft", "agriculture", "recolte", "travaux agricoles"),
        ("tierhaltung", "elevage", "soins aux animaux"),
        ("produktion", "production", "ligne de production", "operateur de production"),
        ("qualitaetskontrolle", "controle qualite", "inspection qualite"),
        ("verpackung", "conditionnement", "emballage"),
        ("lebensmittelproduktion", "industrie agroalimentaire", "transformation alimentaire"),
        ("fotografie", "photographie", "retouche photo"),
        ("grafikdesign", "design graphique", "mise en page"),
        ("teamfaehigkeit", "travail en equipe", "esprit d'equipe"),
        ("zuverlaessigkeit", "fiabilite", "serieux"),
        ("kommunikationsfaehigkeit", "aisance relationnelle", "qualites de communication"),
        ("kundenorientierung", "sens du service", "orientation client"),
        ("belastbarkeit", "resistance au stress", "gestion de la pression"),
        ("selbststaendigkeit", "autonomie", "travail en autonomie"),
        ("flexibilitaet", "flexibilite", "adaptabilite"),
        ("sorgfalt", "souci du detail", "rigueur"),
        ("lernbereitschaft", "envie d'apprendre", "capacite d'apprentissage"),
        ("fuehrungserfahrung", "encadrement d'equipe", "management d'equipe"),
        ("schichtbereitschaft", "travail poste", "horaires decales", "travail le week-end"),
        ("koerperlichearbeit", "travail physique", "port de charges"),
        ("reisebereitschaft", "disponibilite pour deplacements", "deplacements frequents"),
    ),
    "nl": (
        ("pflege", "verpleging", "verzorging", "verzorgende ig", "verpleegkundige"),
        ("betreuung", "begeleiding", "persoonlijke begeleiding"),
        ("erstehilfe", "ehbo", "eerste hulp"),
        ("hygiene", "hygiene", "desinfectie", "hygienevoorschriften"),
        ("physiotherapie", "fysiotherapie", "revalidatie"),
        ("apotheke", "apotheek", "apothekersassistent"),
        ("kueche", "keuken", "bereiden van gerechten", "kok"),
        ("service_gastro", "bediening", "gastvrijheid", "serveren"),
        ("barista", "barman", "cocktails", "barwerk"),
        ("haccp", "haccp", "voedselveiligheid"),
        ("baeckerei", "bakkerij", "banketbakkerij", "bakker"),
        ("reinigung", "schoonmaak", "schoonmaker", "interieurverzorging"),
        ("waescherei", "wasserij", "stomerij"),
        ("hausmeister", "gebouwbeheer", "conciërge", "klein onderhoud"),
        ("wartung", "onderhoud", "reparatie van machines", "preventief onderhoud", "storingen verhelpen"),
        ("lager", "magazijn", "magazijnbeheer", "magazijnmedewerker"),
        ("stapler", "heftruck", "heftruckchauffeur", "reachtruck"),
        ("kommissionierung", "orderpicken", "orderverzamelen"),
        ("disposition", "planning van ritten", "transportplanning"),
        ("kasse", "kassa", "afrekenen", "kassamedewerker"),
        ("verkauf", "verkoop", "verkoper", "winkelmedewerker"),
        ("kundenberatung", "klantadvies", "klantcontact"),
        ("inventur", "inventarisatie", "voorraadtelling"),
        ("maurer", "metselwerk", "metselaar"),
        ("maler", "schilderwerk", "schilder", "stukadoor"),
        ("fliesen", "tegelzetten", "tegelzetter"),
        ("elektroinstallation", "elektrotechniek", "elektricien", "elektrische installaties"),
        ("sanitaer", "loodgieterswerk", "loodgieter", "installatietechniek"),
        ("schweissen", "lassen", "lasser", "tig-lassen"),
        ("montage", "montage", "assemblage", "machines monteren"),
        ("tischlerei", "timmerwerk", "timmerman", "meubelmakerij"),
        ("metallbau", "constructiewerk", "staalconstructies", "bankwerker"),
        ("kfz_mechatronik", "automonteur", "autotechniek", "storingdiagnose"),
        ("hydraulik", "hydrauliek", "pneumatiek"),
        ("buchhaltung", "boekhouding", "boekhouder", "administratie voeren"),
        ("sachbearbeitung", "administratieve verwerking", "dossierbehandeling"),
        ("einkauf", "inkoop", "bestellingen plaatsen"),
        ("kinderbetreuung", "kinderopvang", "pedagogisch medewerker", "bso"),
        ("paedagogik", "pedagogiek", "pedagogisch werk"),
        ("sozialarbeit", "maatschappelijk werk", "sociaal werker"),
        ("unterricht", "lesgeven", "onderwijs", "docent"),
        ("objektschutz", "beveiliging", "beveiliger", "toegangscontrole"),
        ("arbeitssicherheit", "arbeidsveiligheid", "vca", "veiligheidsvoorschriften"),
        ("landwirtschaft", "landbouw", "oogst", "akkerbouw"),
        ("tierhaltung", "veehouderij", "dierverzorging"),
        ("produktion", "productie", "productielijn", "productiemedewerker"),
        ("qualitaetskontrolle", "kwaliteitscontrole", "kwaliteitsinspectie"),
        ("verpackung", "verpakken", "inpakwerk"),
        ("lebensmittelproduktion", "voedingsmiddelenindustrie", "voedselverwerking"),
        ("fotografie", "fotografie", "fotobewerking"),
        ("grafikdesign", "grafisch ontwerp", "opmaak"),
        ("teamfaehigkeit", "teamwerk", "in teamverband werken"),
        ("zuverlaessigkeit", "betrouwbaarheid", "verantwoordelijkheidsgevoel"),
        ("kommunikationsfaehigkeit", "communicatieve vaardigheden"),
        ("kundenorientierung", "klantgerichtheid", "servicegerichtheid"),
        ("belastbarkeit", "stressbestendigheid"),
        ("selbststaendigkeit", "zelfstandigheid", "zelfstandig kunnen werken"),
        ("flexibilitaet", "flexibiliteit", "aanpassingsvermogen"),
        ("sorgfalt", "oog voor detail", "nauwkeurigheid"),
        ("lernbereitschaft", "leergierigheid", "bereid om te leren"),
        ("fuehrungserfahrung", "leidinggevende ervaring", "aansturen van een team"),
        ("schichtbereitschaft", "ploegendienst", "bereid in ploegen te werken", "weekenddiensten"),
        ("koerperlichearbeit", "fysiek werk", "tillen"),
        ("reisebereitschaft", "bereidheid tot reizen"),
    ),
}


ALL_SKILLS: tuple[tuple[str, ...], ...] = (
    IT_SKILLS + PROFESSION_SKILLS + FURTHER_FIELD_SKILLS
)
