"""The skill gazetteer: what a job advert can ask for, and how it spells it.

Separated from the matching logic because it is data, not code, and because
it is meant to grow. Adding a trade means adding a line here; nothing else
in the project changes.

Each entry is ``(id, label, category, *aliases)``. The label is always
usable as an alias, so it is not repeated. Aliases carry the spellings that
actually occur: the German name beside the English one, the abbreviation
beside the full form, and the ASCII spelling beside the umlaut one where
people type both.

Matching is case-insensitive and umlaut-insensitive (see ``normalize``), so
aliases are written in whatever form reads most clearly.

Deliberately absent: names that collide with ordinary words. "Go" and "R"
are real languages, but an advert saying "go live" must not acquire a Go
requirement, so they are reachable through unambiguous aliases only. The
same guard lives in ``skills_lexicon.AMBIGUOUS_ALIASES``.
"""

# --------------------------------------------------------------------------
# Software and IT
# --------------------------------------------------------------------------

IT_SKILLS: tuple[tuple[str, ...], ...] = (
    # --- programming languages ---------------------------------------------
    ("python", "Python", "language"),
    ("csharp", "C#", "language", "c sharp", "csharp"),
    ("cpp", "C++", "language", "cpp"),
    ("clang", "C", "language", "c-programmierung", "ansi c", "embedded c"),
    ("java", "Java", "language"),
    ("javascript", "JavaScript", "language", "js", "ecmascript"),
    ("typescript", "TypeScript", "language", "ts"),
    ("php", "PHP", "language"),
    ("ruby", "Ruby", "language"),
    ("kotlin", "Kotlin", "language"),
    ("swift", "Swift", "language"),
    ("scala", "Scala", "language"),
    ("golang", "Go", "language", "golang", "go-entwicklung", "go developer"),
    ("rlang", "R", "language", "r-programmierung", "sprache r", "r language", "r studio", "rstudio"),
    ("rust", "Rust", "language"),
    ("perl", "Perl", "language"),
    ("abap", "ABAP", "language"),
    ("matlab", "MATLAB", "language", "simulink"),
    ("vba", "VBA", "language", "visual basic for applications", "visual basic", "vb.net"),
    ("dart", "Dart", "language"),
    ("objectivec", "Objective-C", "language", "objective c"),
    ("groovy", "Groovy", "language"),
    ("lua", "Lua", "language"),
    ("elixir", "Elixir", "language", "erlang"),
    ("haskell", "Haskell", "language", "f#", "ocaml"),
    ("assembler", "Assembler", "language", "assemblersprache"),
    ("cobol", "COBOL", "language", "fortran", "pascal", "delphi"),
    ("vhdl", "VHDL", "language", "verilog", "systemverilog"),
    # --- shells and scripting ----------------------------------------------
    ("bash", "Bash", "language", "shell", "shellskripte", "shell scripting", "sh", "zsh"),
    ("powershell", "PowerShell", "language", "power shell", "powershell dsc"),
    ("batch", "Batch", "language", "batch-skripte", "cmd-skripte"),
    # --- .NET ---------------------------------------------------------------
    ("dotnet", ".NET", "framework", "dotnet", ".net core", ".net framework", "net framework"),
    ("aspnet", "ASP.NET", "framework", "asp net", "aspnet core", "asp.net mvc"),
    ("entityframework", "Entity Framework", "framework", "ef core", "entityframework"),
    ("wpf", "WPF", "framework", "windows presentation foundation", "winforms", "windows forms"),
    ("blazor", "Blazor", "framework"),
    ("xamarin", "Xamarin", "framework", "maui", ".net maui"),
    # --- web frontend -------------------------------------------------------
    ("html", "HTML", "web", "html5"),
    ("css", "CSS", "web", "css3", "scss", "sass", "less"),
    ("react", "React", "web", "react.js", "reactjs", "redux", "react hooks"),
    ("angular", "Angular", "web", "angularjs", "rxjs"),
    ("vue", "Vue", "web", "vue.js", "vuejs", "nuxt"),
    ("svelte", "Svelte", "web", "sveltekit"),
    ("nextjs", "Next.js", "web", "nextjs", "remix"),
    ("tailwind", "Tailwind", "web", "tailwind css", "bootstrap", "material ui", "mui"),
    ("jquery", "jQuery", "web"),
    ("bundler", "Webpack", "web", "vite", "rollup", "babel", "esbuild"),
    ("wcag", "Barrierefreiheit", "web", "wcag", "accessibility", "bitv", "aria"),
    # --- web backend --------------------------------------------------------
    ("nodejs", "Node.js", "web", "nodejs", "node js", "express", "nestjs", "deno"),
    ("rest", "REST", "web", "rest-api", "restful", "rest api", "restful api", "openapi", "swagger"),
    ("graphql", "GraphQL", "web"),
    ("soap", "SOAP", "web", "wsdl", "xml-schnittstellen"),
    ("grpc", "gRPC", "web", "protobuf", "protocol buffers"),
    ("websocket", "WebSocket", "web", "websockets", "socket.io"),
    ("django", "Django", "web"),
    ("flask", "Flask", "web", "fastapi"),
    ("spring", "Spring", "web", "spring boot", "springboot", "hibernate", "jpa"),
    ("laravel", "Laravel", "web", "symfony", "codeigniter"),
    ("rails", "Ruby on Rails", "web", "rails"),
    ("streamlit", "Streamlit", "web", "dash", "gradio"),
    ("messaging", "Message Broker", "web", "rabbitmq", "kafka", "apache kafka", "activemq", "celery", "redis queue"),
    # --- mobile --------------------------------------------------------------
    ("android", "Android", "mobile", "android sdk", "jetpack compose"),
    ("ios", "iOS", "mobile", "swiftui", "uikit", "xcode"),
    ("flutter", "Flutter", "mobile"),
    ("reactnative", "React Native", "mobile", "ionic", "cordova"),
    # --- databases -----------------------------------------------------------
    ("sql", "SQL", "database", "sql-kenntnisse", "structured query language", "sql-abfragen"),
    ("mysql", "MySQL", "database", "mariadb"),
    ("postgresql", "PostgreSQL", "database", "postgres"),
    ("mssql", "Microsoft SQL Server", "database", "ms sql", "mssql", "sql server", "t-sql", "tsql", "ssms"),
    ("oracledb", "Oracle Database", "database", "oracle db", "pl/sql", "plsql"),
    ("db2", "Db2", "database", "sybase", "informix"),
    ("mongodb", "MongoDB", "database", "mongo", "documentdb"),
    ("redis", "Redis", "database", "memcached"),
    ("sqlite", "SQLite", "database"),
    ("elasticsearch", "Elasticsearch", "database", "elastic search", "opensearch", "solr", "lucene"),
    ("bigquery", "BigQuery", "database", "google bigquery"),
    ("snowflake", "Snowflake", "database", "redshift", "synapse"),
    ("nosql", "NoSQL", "database", "cassandra", "dynamodb", "cosmos db", "couchbase"),
    ("graphdb", "Graphdatenbanken", "database", "neo4j", "graph database", "sparql"),
    ("timeseries", "Zeitreihendatenbanken", "database", "influxdb", "timescaledb", "prometheus tsdb"),
    ("datamodeling", "Datenmodellierung", "database", "data modeling", "datenmodell", "datenbankdesign", "normalisierung", "er-modell"),
    ("dbadmin", "Datenbankadministration", "database", "database administration", "dba", "indexoptimierung", "query tuning", "performance tuning"),
    # --- data and analytics --------------------------------------------------
    ("pandas", "pandas", "data", "polars"),
    ("numpy", "NumPy", "data", "scipy"),
    ("scikitlearn", "scikit-learn", "data", "sklearn", "scikit learn", "xgboost", "lightgbm"),
    ("tableau", "Tableau", "data"),
    ("powerbi", "Power BI", "data", "powerbi", "microsoft power bi", "dax", "power query"),
    ("qlik", "Qlik", "data", "qlikview", "qlik sense", "looker", "micro strategy"),
    ("excel", "Excel", "data", "microsoft excel", "ms excel", "pivot-tabellen", "pivottabellen", "sverweis", "vlookup"),
    ("spark", "Apache Spark", "data", "pyspark", "spark", "databricks", "hadoop", "hive"),
    ("etl", "ETL", "data", "etl-prozesse", "datenpipelines", "data pipeline", "elt", "ssis", "talend", "airflow", "apache airflow", "dbt"),
    ("datawarehouse", "Data Warehouse", "data", "dwh", "data lake", "lakehouse", "star schema", "sternschema"),
    ("statistics", "Statistik", "data", "statistics", "deskriptive statistik", "statistische analyse", "hypothesentest", "regression"),
    ("dataviz", "Datenvisualisierung", "data", "data visualization", "dashboards", "reporting", "ssrs", "berichtswesen"),
    ("dataquality", "Datenqualität", "data", "data quality", "data cleaning", "datenbereinigung", "stammdatenpflege", "datenvalidierung", "datenpflege"),
    ("datagovernance", "Data Governance", "data", "datenkatalog", "data lineage", "mdm", "stammdatenmanagement"),
    # --- AI / ML --------------------------------------------------------------
    ("machinelearning", "Maschinelles Lernen", "ai", "machine learning", "ml", "maschinelles lernen", "predictive modeling"),
    ("deeplearning", "Deep Learning", "ai", "neuronale netze", "neural networks", "tiefes lernen", "cnn", "transformer"),
    ("llm", "Große Sprachmodelle", "ai", "large language models", "llm", "llms", "sprachmodelle", "gpt", "chatgpt"),
    ("nlp", "NLP", "ai", "natural language processing", "computerlinguistik", "sprachverarbeitung", "texterkennung"),
    ("computervision", "Computer Vision", "ai", "bildverarbeitung", "bilderkennung", "ocr", "opencv"),
    ("tensorflow", "TensorFlow", "ai", "keras"),
    ("pytorch", "PyTorch", "ai", "huggingface", "hugging face", "transformers"),
    ("ai_general", "Künstliche Intelligenz", "ai", "artificial intelligence", "ki", "ai"),
    ("aiagents", "KI-Agenten", "ai", "ai agents", "agentic", "ki agenten", "langchain"),
    ("ollama", "Ollama", "ai", "llama.cpp", "vllm"),
    ("rag", "RAG", "ai", "retrieval augmented generation", "vektordatenbank", "vector database", "embeddings"),
    ("promptengineering", "Prompt Engineering", "ai", "prompting"),
    ("mlops", "MLOps", "ai", "mlflow", "modell-deployment", "model deployment", "feature store"),
    # --- infrastructure --------------------------------------------------------
    ("linux", "Linux", "infra", "unix", "ubuntu", "debian", "red hat", "rhel", "centos", "suse", "linux-administration"),
    ("windowsserver", "Windows Server", "infra", "windows-server", "windows server 2022", "server 2019"),
    ("docker", "Docker", "infra", "container", "containerisierung", "docker compose", "podman", "containerization"),
    ("kubernetes", "Kubernetes", "infra", "k8s", "openshift", "helm", "rancher", "argocd", "argo cd"),
    ("ansible", "Ansible", "infra"),
    ("terraform", "Terraform", "infra", "infrastructure as code", "iac", "pulumi", "cloudformation", "bicep"),
    ("puppet", "Puppet", "infra", "chef", "saltstack"),
    ("vmware", "VMware", "infra", "vsphere", "esxi", "virtualisierung", "virtualization", "vcenter"),
    ("proxmox", "Proxmox", "infra", "kvm", "xen"),
    ("hyperv", "Hyper-V", "infra", "hyperv"),
    ("citrix", "Citrix", "infra", "terminalserver", "remote desktop services", "rds", "vdi"),
    ("truenas", "TrueNAS", "infra", "freenas", "nas", "nas-systeme", "san", "storage", "speicherverwaltung"),
    ("nginx", "Nginx", "infra", "apache", "webserver", "iis", "haproxy", "traefik"),
    ("aws", "AWS", "cloud", "amazon web services", "ec2", "s3", "lambda", "eks", "ecs"),
    ("azure", "Azure", "cloud", "microsoft azure", "azure devops", "azure functions", "entra"),
    ("gcp", "Google Cloud", "cloud", "gcp", "google cloud platform"),
    ("cloud_general", "Cloud", "cloud", "cloud-technologien", "cloud computing", "hybrid cloud", "multi-cloud"),
    ("backup", "Backup", "infra", "datensicherung", "restore", "disaster recovery", "veeam", "notfallkonzept"),
    ("monitoring", "Monitoring", "infra", "überwachung", "prometheus", "grafana", "nagios", "zabbix", "checkmk", "icinga"),
    ("observability", "Observability", "infra", "elk", "elastic stack", "splunk", "datadog", "new relic", "sentry", "loki", "logging"),
    ("intune", "Intune", "infra", "sccm", "mecm", "wsus", "gruppenrichtlinien", "group policy", "mdm-verwaltung", "endpoint management"),
    ("embedded", "Embedded Systems", "infra", "mikrocontroller", "microcontroller", "arduino", "raspberry pi", "fpga", "rtos", "bare metal"),
    ("fieldbus", "Feldbus", "infra", "can-bus", "modbus", "profinet", "profibus", "opc ua", "mqtt", "iot", "industrie 4.0"),
    # --- networking -------------------------------------------------------------
    ("networking", "Netzwerk", "network", "netzwerke", "networking", "netzwerktechnik", "lan", "wan", "netzwerkadministration"),
    ("tcpip", "TCP/IP", "network", "tcp ip", "subnetting", "ipv6"),
    ("dns", "DNS", "network", "dhcp", "namensauflösung"),
    ("vpn", "VPN", "network", "ipsec", "wireguard", "openvpn"),
    ("firewall", "Firewall", "network", "firewalls", "fortigate", "pfsense", "sophos", "palo alto", "checkpoint"),
    ("routing", "Routing", "network", "switching", "bgp", "ospf", "vlan", "mpls", "sd-wan", "spanning tree"),
    ("ciscohw", "Cisco", "network", "juniper", "hpe aruba", "ubiquiti", "ccna", "ccnp"),
    ("wlan", "WLAN", "network", "wifi", "wi-fi", "access points", "funknetz"),
    ("activedirectory", "Active Directory", "network", "ad", "ldap", "entra id", "azure ad", "domänencontroller"),
    ("exchange", "Exchange", "network", "microsoft exchange", "outlook", "mail-server", "smtp", "postfix"),
    ("m365", "Microsoft 365", "network", "office 365", "o365", "ms office", "microsoft office", "sharepoint online", "teams"),
    ("telefonie", "Telefonie", "network", "voip", "sip", "tk-anlage", "unified communications"),
    # --- security ---------------------------------------------------------------
    ("security", "IT-Sicherheit", "security", "it-security", "informationssicherheit", "cyber security", "cybersecurity", "sicherheitskonzepte"),
    ("datenschutz", "Datenschutz", "security", "dsgvo", "gdpr", "datenschutzgrundverordnung", "privacy"),
    ("pentest", "Penetrationstest", "security", "pentest", "penetration testing", "schwachstellenanalyse", "vulnerability", "burp suite", "nessus", "metasploit"),
    ("siem", "SIEM", "security", "soc", "security operations", "incident response", "threat detection", "ids", "ips"),
    ("iam", "Identity Management", "security", "iam", "berechtigungsverwaltung", "rechteverwaltung", "single sign-on", "sso", "oauth", "saml", "keycloak", "pki", "zertifikatsverwaltung"),
    ("isms", "ISO 27001", "security", "isms", "bsi grundschutz", "it-grundschutz", "nis2", "tisax", "sicherheitsaudit"),
    ("kryptographie", "Kryptographie", "security", "verschlüsselung", "encryption", "tls", "hsm"),
    # --- tools and process -------------------------------------------------------
    ("git", "Git", "tool", "github", "gitlab", "bitbucket", "versionsverwaltung", "version control", "svn", "azure repos"),
    ("cicd", "CI/CD", "method", "ci cd", "continuous integration", "continuous delivery", "jenkins", "github actions", "gitlab ci", "teamcity", "bamboo", "deployment-pipeline"),
    ("jira", "Jira", "tool", "confluence", "atlassian", "azure boards", "youtrack"),
    ("ticketsystem", "Ticketsystem", "tool", "ticketing", "servicedesk", "service desk", "helpdesk", "otrs", "jira service management", "zendesk", "freshdesk"),
    ("n8n", "n8n", "tool", "zapier", "make.com", "power automate", "workflow-tools"),
    ("ide", "Visual Studio", "tool", "visual studio code", "vs code", "intellij", "pycharm", "eclipse", "rider", "netbeans"),
    # --- testing ------------------------------------------------------------------
    ("testing", "Testing", "method", "softwaretest", "qualitätssicherung", "quality assurance", "qa", "testautomatisierung", "test automation", "testfälle", "testkonzepte", "testmanagement"),
    ("tdd", "TDD", "method", "test driven development", "unit tests", "unittests", "pytest", "junit", "nunit", "xunit", "jest", "mocha", "testng"),
    ("e2etesting", "End-to-End-Tests", "method", "selenium", "cypress", "playwright", "appium", "robot framework", "ui-tests"),
    ("apitesting", "API-Tests", "method", "postman", "soapui", "rest assured"),
    ("loadtesting", "Lasttests", "method", "jmeter", "loadrunner", "performancetests", "k6", "gatling"),
    ("istqb", "ISTQB", "method", "certified tester"),
    # --- methods --------------------------------------------------------------------
    ("scrum", "Scrum", "method", "agile", "agil", "kanban", "safe", "sprint", "daily", "retrospektive", "scrum master", "product owner"),
    ("devops", "DevOps", "method", "sre", "site reliability", "platform engineering"),
    ("itil", "ITIL", "method", "itsm", "cobit", "service management", "incident management", "problem management"),
    ("waterfall", "Wasserfallmodell", "method", "v-modell", "v-modell xt", "waterfall", "prince2", "pmi", "pmp", "ipma"),
    ("oop", "Objektorientierte Programmierung", "method", "object oriented programming", "oop", "objektorientierung", "vererbung"),
    ("microservices", "Microservices", "method", "microservice", "mikroservices", "serverless", "event-driven", "ereignisgesteuert"),
    ("designpatterns", "Design Patterns", "method", "entwurfsmuster", "clean code", "solid", "refactoring", "code review", "pair programming"),
    ("uml", "UML", "method", "bpmn", "modellierung", "sequenzdiagramm", "aktivitätsdiagramm", "archimate"),
    ("softwarearchitektur", "Softwarearchitektur", "method", "software architecture", "systemarchitektur", "architekturentscheidungen", "domain driven design", "ddd"),
    ("requirements", "Anforderungsanalyse", "method", "requirements engineering", "anforderungsmanagement", "lastenheft", "pflichtenheft", "user stories", "epics"),
    ("documentation", "Dokumentation", "method", "technische dokumentation", "documentation", "betriebshandbuch", "wiki-pflege"),
    ("automation", "Automatisierung", "method", "automation", "prozessautomatisierung", "process automation", "workflow automation", "rpa", "skripting"),
    # --- ERP, CRM, CMS ------------------------------------------------------------------
    ("sap", "SAP", "business", "sap erp", "s/4hana", "sap fi", "sap co", "sap mm", "sap sd", "sap hcm", "sap basis"),
    ("dynamics", "Microsoft Dynamics", "business", "dynamics 365", "navision", "business central", "axapta"),
    ("erp_other", "ERP-Systeme", "business", "odoo", "abas", "proalpha", "infor", "erp-system", "warenwirtschaftssystem"),
    ("salesforce", "Salesforce", "business", "crm", "crm-systeme", "hubspot", "pipedrive"),
    ("cms", "CMS", "business", "wordpress", "typo3", "drupal", "joomla", "contentful", "content management system"),
    ("ecommerce", "E-Commerce", "business", "shopware", "magento", "shopify", "woocommerce", "onlineshop"),
    ("itwo", "iTWO", "business", "rib itwo", "nevaris", "bausoftware"),
)


# --------------------------------------------------------------------------
# Everything else people are hired to do
# --------------------------------------------------------------------------

PROFESSION_SKILLS: tuple[tuple[str, ...], ...] = (
    # --- medicine and health -------------------------------------------------
    ("approbation", "Approbation", "health", "facharzt", "facharztausbildung", "assistenzarzt", "oberarzt", "medical licence"),
    ("diagnostik", "Diagnostik", "health", "anamnese", "befundung", "differentialdiagnose", "diagnosis"),
    ("chirurgie", "Chirurgie", "health", "operationen", "op-assistenz", "surgery", "op-saal", "instrumentieren"),
    ("innere", "Innere Medizin", "health", "kardiologie", "gastroenterologie", "onkologie", "neurologie", "pädiatrie", "gynäkologie", "orthopädie", "urologie", "dermatologie", "psychiatrie"),
    ("anaesthesie", "Anästhesie", "health", "narkose", "intensivmedizin", "beatmung", "anesthesia"),
    ("radiologie", "Radiologie", "health", "röntgen", "mrt", "ct", "sonographie", "ultraschall", "bildgebung"),
    ("notfallmedizin", "Notfallmedizin", "health", "notaufnahme", "rettungsdienst", "notfallsanitäter", "rettungssanitäter", "emergency medicine", "triage"),
    ("patientenversorgung", "Patientenversorgung", "health", "patientenbetreuung", "visite", "patient care", "aufklärungsgespräche"),
    ("zahnmedizin", "Zahnmedizin", "health", "zahnarzt", "prophylaxe", "zahntechnik", "dental", "kieferorthopädie"),
    ("apotheke", "Apotheke", "health", "pharmazie", "arzneimittel", "rezeptur", "pta", "pharmacy", "medikationsberatung"),
    ("veterinaer", "Veterinärmedizin", "health", "tierarzt", "tiermedizin", "veterinary"),
    ("hebamme", "Geburtshilfe", "health", "hebamme", "midwifery", "wochenbett"),
    ("mfa", "Medizinische Fachangestellte", "health", "mfa", "arzthelferin", "praxisorganisation", "blutentnahme", "ekg"),
    ("abrechnung_med", "Medizinische Abrechnung", "health", "goä", "ebm", "drg", "kodierung", "medical coding", "kassenabrechnung"),
    # --- care and social work -------------------------------------------------
    ("pflege", "Pflege", "care", "grundpflege", "behandlungspflege", "altenpflege", "krankenpflege", "nursing", "pflegefachkraft", "gesundheits- und krankenpfleger", "intensivpflege"),
    ("pflegedoku", "Pflegedokumentation", "care", "pflegeplanung", "care documentation", "pflegeprozess"),
    ("wundmanagement", "Wundmanagement", "care", "wundversorgung", "wound care", "dekubitusprophylaxe"),
    ("medikamentengabe", "Medikamentengabe", "care", "medikamentenmanagement", "medication management", "injektionen"),
    ("erstehilfe", "Erste Hilfe", "care", "first aid", "notfallmanagement", "reanimation", "defibrillator"),
    ("hygiene", "Hygiene", "care", "hygienevorschriften", "desinfektion", "disinfection", "hygienestandards", "infektionsschutz"),
    ("betreuung", "Betreuung", "care", "personenbetreuung", "tagesbetreuung", "support work", "eingliederungshilfe", "assistenz"),
    ("therapie", "Therapie", "care", "physiotherapie", "ergotherapie", "logopädie", "rehabilitation", "massage", "manuelle therapie"),
    ("sozialarbeit", "Soziale Arbeit", "care", "sozialpädagogik", "sozialarbeit", "social work", "beratungsgespräche", "case management", "jugendhilfe"),
    ("labor", "Labor", "health", "labortechnik", "laboratory", "probenahme", "mta", "analytik", "laborwerte"),
    # --- education and religion ------------------------------------------------
    ("paedagogik", "Pädagogik", "education", "erziehung", "frühpädagogik", "pedagogy", "erzieher", "erzieherin", "kita", "kindergarten"),
    ("unterricht", "Unterricht", "education", "lehrtätigkeit", "didaktik", "methodik", "teaching", "lehrer", "dozent", "nachhilfe", "seminare"),
    ("bildungsplan", "Bildungsplan", "education", "bildungspläne", "curriculum", "lehrplan", "rahmenplan"),
    ("elternarbeit", "Elternarbeit", "education", "erziehungspartnerschaft", "parent communication", "elterngespräche"),
    ("gruppenleitung", "Gruppenleitung", "education", "gruppenarbeit", "group work", "anleitung", "klassenführung"),
    ("inklusion", "Inklusion", "education", "integration", "heilpädagogik", "sonderpädagogik", "förderbedarf"),
    ("seelsorge", "Seelsorge", "religion", "pastoral", "pastoralarbeit", "spiritual care", "beichte", "geistliche begleitung"),
    ("gottesdienst", "Gottesdienst", "religion", "liturgie", "predigt", "andacht", "worship", "sakramente", "kirchenmusik"),
    ("gemeindearbeit", "Gemeindearbeit", "religion", "gemeindeleitung", "jugendarbeit", "kirchengemeinde", "ehrenamtskoordination"),
    ("theologie", "Theologie", "religion", "religionspädagogik", "theology", "exegese", "kirchenrecht"),
    # --- law, consulting, public sector ------------------------------------------
    ("rechtsberatung", "Rechtsberatung", "legal", "juristische beratung", "legal advice", "gutachten", "rechtsprüfung"),
    ("vertragsrecht", "Vertragsrecht", "legal", "vertragsgestaltung", "vertragsverhandlung", "contract law", "agb", "nda"),
    ("prozessfuehrung", "Prozessführung", "legal", "litigation", "schriftsätze", "gerichtstermine", "mandantenbetreuung"),
    ("rechtsgebiete", "Rechtsgebiete", "legal", "arbeitsrecht", "labour law", "labor law", "tarifrecht", "handelsrecht", "gesellschaftsrecht", "familienrecht", "strafrecht", "mietrecht", "baurecht", "verwaltungsrecht", "sozialrecht"),
    ("notariat", "Notariat", "legal", "beurkundung", "grundbuch", "rechtsanwaltsfachangestellte", "renо", "kanzleiorganisation"),
    ("unternehmensberatung", "Unternehmensberatung", "consulting", "consulting", "prozessberatung", "management consulting", "strategieberatung", "organisationsentwicklung"),
    ("changemanagement", "Change Management", "consulting", "veränderungsmanagement", "transformation", "stakeholder-management", "moderation", "workshops"),
    ("prozessanalyse", "Prozessanalyse", "consulting", "prozessoptimierung", "process improvement", "lean", "six sigma", "kaizen", "kvp", "wertstromanalyse"),
    ("praesentation", "Präsentationen", "consulting", "presentation skills", "powerpoint", "pitch", "kundenpräsentation"),
    ("verwaltung_public", "Öffentliche Verwaltung", "public", "behörde", "bürgerbüro", "verwaltungsfachangestellte", "amtsleitung", "public administration", "ausschreibungsrecht", "vergaberecht", "vob"),
    # --- finance, banking, insurance -----------------------------------------------
    ("buchhaltung", "Buchhaltung", "finance", "finanzbuchhaltung", "rechnungswesen", "bookkeeping", "accounting", "kreditorenbuchhaltung", "debitorenbuchhaltung", "anlagenbuchhaltung"),
    ("lohnbuchhaltung", "Lohnbuchhaltung", "finance", "entgeltabrechnung", "gehaltsabrechnung", "payroll", "lohnsteuer", "sozialversicherung"),
    ("datev", "DATEV", "finance", "lexware", "addison", "sage", "agenda"),
    ("bilanzierung", "Bilanzierung", "finance", "jahresabschluss", "hgb", "ifrs", "financial statements", "monatsabschluss", "konzernabschluss"),
    ("steuerrecht", "Steuerrecht", "finance", "umsatzsteuer", "tax law", "steuererklärung", "steuerberatung", "körperschaftsteuer"),
    ("controlling", "Controlling", "finance", "kostenrechnung", "budgetplanung", "forecasting", "kennzahlen", "kpi", "abweichungsanalyse", "wirtschaftlichkeitsrechnung"),
    ("mahnwesen", "Mahnwesen", "finance", "forderungsmanagement", "dunning", "inkasso", "zahlungsverkehr"),
    ("treasury", "Treasury", "finance", "liquiditätsplanung", "cash management", "finanzierung", "kapitalmarkt"),
    ("bankwesen", "Bankwesen", "banking", "bankkaufmann", "bankkauffrau", "banking", "kontoführung", "filialgeschäft", "bankberatung"),
    ("kreditgeschaeft", "Kreditgeschäft", "banking", "kreditanalyse", "baufinanzierung", "firmenkundenkredit", "lending", "bonitätsprüfung", "rating"),
    ("anlageberatung", "Anlageberatung", "banking", "wertpapiere", "investment", "portfoliomanagement", "vermögensberatung", "fonds", "depot", "börse"),
    ("compliance_fin", "Compliance", "banking", "geldwäscheprävention", "kyc", "know your customer", "aml", "mifid", "wphg", "regulatorik", "meldewesen"),
    ("risikomanagement", "Risikomanagement", "banking", "risk management", "risikoanalyse", "basel", "solvency"),
    ("versicherung", "Versicherung", "insurance", "versicherungskaufmann", "insurance", "policen", "tarifierung", "versicherungsvertrieb"),
    ("schadenregulierung", "Schadenregulierung", "insurance", "schadenbearbeitung", "claims", "leistungsprüfung", "sachverständigengutachten"),
    # --- sales, retail, marketing ---------------------------------------------------
    ("kundenberatung", "Kundenberatung", "sales", "kundenbetreuung", "customer service", "kundenkontakt", "beratung", "kundendienst", "kundenservice"),
    ("verkauf", "Verkauf", "sales", "vertrieb", "sales", "außendienst", "innendienst", "verkaufsgespräche", "verkaufsberatung", "abschlussstärke"),
    ("keyaccount", "Key Account Management", "sales", "key account", "großkundenbetreuung", "account management", "b2b", "b2c", "bestandskundenpflege"),
    ("akquise", "Akquise", "sales", "neukundengewinnung", "lead generation", "kaltakquise", "leadgenerierung", "telefonakquise"),
    ("angebotserstellung", "Angebotserstellung", "sales", "angebotskalkulation", "quotation", "ausschreibungen", "auftragsabwicklung", "auftragsbearbeitung"),
    ("vertriebssteuerung", "Vertriebssteuerung", "sales", "umsatzverantwortung", "sales forecast", "pipeline management", "gebietsverantwortung", "vertriebsziele"),
    ("kasse", "Kassiertätigkeit", "retail", "kassensystem", "kassieren", "cash register", "checkout", "kassenabschluss"),
    ("warenpraesentation", "Warenpräsentation", "retail", "warenverräumung", "merchandising", "regalpflege", "visual merchandising", "warenannahme"),
    ("filialleitung", "Filialleitung", "retail", "marktleitung", "storemanagement", "store manager", "personaleinsatzplanung", "umsatzsteuerung"),
    ("inventur", "Inventur", "retail", "bestandskontrolle", "stocktaking", "warenwirtschaft", "bestellwesen"),
    ("reklamation", "Reklamationsbearbeitung", "sales", "beschwerdemanagement", "complaint handling", "retourenbearbeitung"),
    ("marketing", "Marketing", "marketing", "onlinemarketing", "online marketing", "digital marketing", "kampagnen", "marketingstrategie", "markenführung", "branding"),
    ("seo", "SEO", "marketing", "sea", "suchmaschinenoptimierung", "google ads", "adwords", "ppc", "performance marketing"),
    ("socialmedia", "Social Media", "marketing", "social media marketing", "instagram", "linkedin", "tiktok", "community management", "redaktionsplan"),
    ("contentmarketing", "Content Marketing", "marketing", "contenterstellung", "copywriting", "texten", "newsletter", "e-mail-marketing", "blogbeiträge"),
    ("webanalyse", "Webanalyse", "marketing", "google analytics", "matomo", "tracking", "conversion", "a/b-tests"),
    ("pr", "Öffentlichkeitsarbeit", "marketing", "public relations", "pressearbeit", "pressemitteilungen", "unternehmenskommunikation"),
    # --- design, media, creative -------------------------------------------------------
    ("grafikdesign", "Grafikdesign", "design", "graphic design", "mediengestaltung", "layout", "typografie", "typography", "satz", "druckvorstufe", "reinzeichnung"),
    ("adobe", "Adobe Creative Suite", "design", "photoshop", "illustrator", "indesign", "after effects", "premiere", "lightroom"),
    ("uiux", "UI/UX", "design", "ux", "ui design", "usability", "wireframes", "prototyping", "user research", "design system"),
    ("figma", "Figma", "design", "adobe xd", "sketch", "invision"),
    ("corporatedesign", "Corporate Design", "design", "brand design", "styleguide", "logoentwicklung", "gestaltungsrichtlinien"),
    ("illustration", "Illustration", "design", "zeichnen", "storyboard", "konzeptzeichnung"),
    ("motiondesign", "Motion Design", "design", "animation", "3d-animation", "videoanimation", "compositing"),
    ("dreid", "3D-Modellierung", "design", "3d modelling", "blender", "maya", "3ds max", "cinema 4d", "rendering", "texturing"),
    ("houdini", "Houdini", "design", "sidefx houdini", "3d-simulation", "vfx", "partikelsimulation"),
    ("fotografie", "Fotografie", "media", "photography", "bildbearbeitung", "fotoshooting", "studiofotografie"),
    ("videoproduktion", "Videoproduktion", "media", "videoschnitt", "video editing", "kamera", "filmproduktion", "livestream", "streaming"),
    ("tontechnik", "Tontechnik", "media", "audiotechnik", "sound design", "mischpult", "beschallung", "mikrofonierung"),
    ("veranstaltungstechnik", "Veranstaltungstechnik", "media", "bühnentechnik", "lichttechnik", "event technology", "rigging"),
    ("redaktion", "Redaktion", "media", "journalismus", "recherche", "lektorat", "korrektorat", "editing", "redaktionelle arbeit"),
    ("uebersetzung", "Übersetzung", "media", "translation", "dolmetschen", "interpreting", "lokalisierung", "localisation", "cat-tools", "trados"),
    # --- engineering and architecture ---------------------------------------------------
    ("konstruktion", "Konstruktion", "engineering", "design engineering", "bauteilkonstruktion", "entwicklungskonstruktion", "produktentwicklung"),
    ("cad", "CAD", "engineering", "autocad", "solidworks", "catia", "inventor", "creo", "nx", "solid edge"),
    ("fem", "FEM-Berechnung", "engineering", "finite elemente", "simulation", "strukturanalyse", "cfd", "strömungssimulation"),
    ("statik", "Statik", "engineering", "tragwerksplanung", "structural analysis", "lastannahmen", "bemessung"),
    ("projektierung", "Projektierung", "engineering", "anlagenplanung", "auslegung", "spezifikation"),
    ("inbetriebnahme", "Inbetriebnahme", "engineering", "commissioning", "anlagenoptimierung", "störungsbehebung", "serviceeinsätze"),
    ("normen", "Normen und Richtlinien", "engineering", "din", "iso", "en-normen", "vde", "ce-kennzeichnung", "maschinenrichtlinie", "standards compliance"),
    ("messtechnik", "Messtechnik", "engineering", "prüftechnik", "kalibrierung", "toleranzen", "qualitätsmanagement", "iso 9001", "fmea", "8d-report", "apqp", "ppap"),
    ("prototypenbau", "Prototypenbau", "engineering", "musterbau", "versuchsaufbau", "prototyping engineering"),
    ("architektur", "Architektur", "architecture", "architect", "hochbau", "entwurfsplanung", "gebäudeplanung", "architekturbüro"),
    ("bauplanung", "Bauplanung", "architecture", "genehmigungsplanung", "ausführungsplanung", "werkplanung", "leistungsphasen", "bauantrag"),
    ("bauleitung", "Bauleitung", "architecture", "site management", "baustellenkoordination", "bauüberwachung", "abnahmen", "baustellenleitung"),
    ("bim", "BIM", "architecture", "building information modeling", "revit", "archicad", "allplan", "vectorworks", "ifc"),
    ("ausschreibung", "Ausschreibung", "architecture", "hoai", "leistungsphasen", "vergabe", "lv-erstellung", "leistungsverzeichnis", "kostenschätzung", "kostenkontrolle", "nachtragsmanagement"),
    ("stadtplanung", "Stadtplanung", "architecture", "urban planning", "bauleitplanung", "bebauungsplan", "landschaftsarchitektur"),
    # --- construction and trades ------------------------------------------------------------
    ("montage", "Montage", "trade", "demontage", "assembly", "baugruppenmontage", "endmontage", "vormontage"),
    ("schweissen", "Schweißen", "trade", "wig", "mag", "mig", "welding", "schweisstechnik", "schweißerprüfung", "löten", "hartlöten"),
    ("elektroinstallation", "Elektroinstallation", "trade", "elektromontage", "schaltschrankbau", "electrical installation", "elektriker", "elektroniker", "verkabelung", "elektrotechnik"),
    ("sps", "SPS", "trade", "speicherprogrammierbare steuerung", "siemens s7", "plc", "tia portal", "steuerungstechnik", "automatisierungstechnik"),
    ("hydraulik", "Hydraulik", "trade", "pneumatik", "hydraulics", "pneumatics", "antriebstechnik"),
    ("cnc", "CNC", "trade", "cnc-fräsen", "cnc-drehen", "zerspanung", "cnc machining", "drehen", "fräsen", "schleifen"),
    ("sanitaer", "Sanitär", "trade", "heizung", "klima", "shk", "lüftung", "plumbing", "hvac", "kältetechnik", "anlagenmechaniker"),
    ("technischezeichnung", "Technische Zeichnungen", "trade", "technical drawings", "schaltpläne", "blueprints", "stücklisten", "zeichnungslesen"),
    ("maurer", "Maurerarbeiten", "construction", "beton", "schalung", "bewehrung", "mauerwerk", "masonry", "hochbau-ausführung"),
    ("trockenbau", "Trockenbau", "construction", "innenausbau", "drywall", "dämmung", "estrich"),
    ("dach", "Dachdeckerarbeiten", "construction", "dachdecker", "abdichtung", "roofing", "zimmerer", "holzbau"),
    ("fliesen", "Fliesenlegerarbeiten", "construction", "fliesenleger", "bodenbelag", "tiling", "parkett"),
    ("maler", "Malerarbeiten", "construction", "maler", "lackierer", "painting", "tapezieren", "spachteln"),
    ("geruestbau", "Gerüstbau", "construction", "scaffolding", "gerüstmontage"),
    ("tiefbau", "Tiefbau", "construction", "kanalbau", "straßenbau", "erdarbeiten", "civil engineering", "rohrleitungsbau"),
    ("baumaschinen", "Baumaschinen", "construction", "bagger", "radlader", "baumaschinenführer", "kranführer", "kranschein"),
    ("kfz", "Kfz-Technik", "automotive", "fahrzeugtechnik", "kfz-mechatroniker", "automotive", "motorinstandsetzung", "fahrwerk", "bremsen"),
    ("kfzdiagnose", "Fahrzeugdiagnose", "automotive", "diagnosegerät", "fehlerauslese", "hu", "au", "abgasuntersuchung", "hauptuntersuchung"),
    ("lackierung", "Fahrzeuglackierung", "automotive", "karosseriebau", "unfallinstandsetzung", "smart repair"),
    # --- logistics and driving ---------------------------------------------------------------
    ("fahrerkarte", "Fahrerkarte", "logistics", "bkrfqg", "berufskraftfahrerqualifikation", "modul 95", "schlüsselzahl 95", "fahrpersonalrecht", "lenkzeiten"),
    ("gefahrgut", "Gefahrgut", "logistics", "adr", "adr-schein", "dangerous goods", "gefahrgutbeauftragter"),
    ("stapler", "Staplerschein", "logistics", "gabelstapler", "flurförderzeug", "forklift", "hubwagen", "schubmaststapler"),
    ("kommissionierung", "Kommissionierung", "logistics", "picking", "packen", "versandvorbereitung", "wareneingang", "warenausgang"),
    ("ladungssicherung", "Ladungssicherung", "logistics", "load securing", "verladung", "be- und entladung"),
    ("lager", "Lagerwirtschaft", "logistics", "lagerverwaltung", "lagerhaltung", "warehouse", "bestandsführung", "lagerlogistik", "fachkraft für lagerlogistik"),
    ("disposition", "Disposition", "logistics", "tourenplanung", "routenplanung", "dispatching", "fuhrparkmanagement", "speditionsabwicklung"),
    ("zoll", "Zollabwicklung", "logistics", "customs", "außenhandel", "export", "import", "atlas", "incoterms"),
    ("supplychain", "Supply Chain", "logistics", "lieferkette", "materialwirtschaft", "bedarfsplanung", "logistikplanung"),
    ("personenbefoerderung", "Personenbeförderung", "logistics", "p-schein", "busfahrer", "taxischein", "fahrgastbetreuung"),
    ("luftfahrt", "Luftfahrt", "aviation", "flugbetrieb", "aviation", "pilotenlizenz", "atpl", "ppl", "cabin crew", "flugbegleiter", "luftsicherheit", "part-145", "easa"),
    ("schifffahrt", "Schifffahrt", "logistics", "nautik", "maritime", "hafenlogistik", "seefracht"),
    ("bahn", "Bahnbetrieb", "logistics", "triebfahrzeugführer", "rangieren", "eisenbahn", "schienenverkehr"),
    # --- hospitality and food ------------------------------------------------------------------
    ("kueche", "Küche", "hospitality", "kuechenerfahrung", "zubereitung", "speisenzubereitung", "kitchen", "food preparation", "koch", "köchin", "gastronomie", "à la carte", "a la carte", "beikoch", "chef de partie"),
    ("haccp", "HACCP", "hospitality", "lebensmittelhygiene", "food safety", "lebensmittelrecht"),
    ("service_gastro", "Service", "hospitality", "servicekraft", "bedienung", "gastronomieservice", "waiting tables", "restaurantfachmann", "gästebetreuung"),
    ("barista", "Barista", "hospitality", "bar", "cocktails", "bartender", "barkeeper", "getränkekunde"),
    ("kalkulation", "Kalkulation", "hospitality", "speisenkalkulation", "wareneinsatz", "costing", "menüplanung"),
    ("bankett", "Bankett", "hospitality", "catering", "veranstaltungsgastronomie", "events", "eventmanagement", "veranstaltungsplanung", "messeorganisation"),
    ("housekeeping", "Housekeeping", "hospitality", "zimmerreinigung", "etagenservice", "wäschemanagement"),
    ("rezeption", "Rezeption", "hospitality", "empfang", "front office", "check-in", "reception", "hotelsoftware", "opera pms", "reservierung"),
    ("baeckerei", "Bäckerei", "hospitality", "konditorei", "backwaren", "patisserie", "fleischerei", "metzgerei", "lebensmittelhandwerk"),
    # --- cleaning and facility -------------------------------------------------------------------
    ("reinigung", "Reinigung", "facility", "unterhaltsreinigung", "grundreinigung", "glasreinigung", "gebäudereinigung", "cleaning", "sonderreinigung", "reinigungskraft", "raumpflege", "büroreinigung", "treppenhausreinigung"),
    ("reinigungsmittel", "Reinigungsmittel", "facility", "reinigungschemie", "dosierung", "cleaning agents", "pflegemittel"),
    ("reinigungsmaschinen", "Reinigungsmaschinen", "facility", "scheuersaugmaschine", "bodenreinigungsmaschine", "cleaning machines", "einscheibenmaschine"),
    ("hausmeister", "Hausmeistertätigkeiten", "facility", "hausmeister", "facility management", "haustechnik", "gebäudetechnik", "kleinreparaturen", "objektbetreuung"),
    ("gartenpflege", "Gartenpflege", "facility", "grünpflege", "landschaftspflege", "groundskeeping", "gala-bau", "baumpflege"),
    ("wartung", "Wartung", "facility", "instandhaltung", "instandsetzung", "maintenance", "reparatur", "repair", "wartungsplanung", "prüffristen"),
    ("waescherei", "Wäscherei", "facility", "textilreinigung", "laundry", "mangeln", "chemische reinigung"),
    # --- textile, crafts, beauty ---------------------------------------------------------------------
    ("naeharbeiten", "Näharbeiten", "textile", "nähen", "nähmaschine", "sewing", "schneiderei", "änderungsschneiderei", "overlock", "sticken"),
    ("zuschnitt", "Zuschnitt", "textile", "schnittmuster", "pattern making", "gradieren", "maßanfertigung", "modellentwicklung"),
    ("textilverarbeitung", "Textilverarbeitung", "textile", "textiltechnik", "stoffkunde", "konfektion", "polsterei", "raumausstattung"),
    ("friseur", "Friseurhandwerk", "beauty", "friseur", "haarschnitt", "coloration", "färben", "hairdressing", "styling", "hochsteckfrisuren"),
    ("kosmetik", "Kosmetik", "beauty", "kosmetikerin", "gesichtsbehandlung", "maniküre", "pediküre", "wimpernverlängerung", "make-up"),
    ("massage_beauty", "Wellness", "beauty", "spa", "wellnessanwendungen", "sauna"),
    ("tattoo", "Tätowieren", "beauty", "piercing", "permanent make-up"),
    ("goldschmied", "Goldschmiedearbeiten", "textile", "schmuckherstellung", "gravur", "uhrmacher", "feinmechanik"),
    ("floristik", "Floristik", "textile", "blumenbinderei", "gestecke", "floristry"),
    # --- agriculture, environment, animals --------------------------------------------------------------
    ("landwirtschaft", "Landwirtschaft", "agriculture", "agriculture", "ackerbau", "ernte", "aussaat", "landwirt", "farming"),
    ("landmaschinen", "Landmaschinen", "agriculture", "traktor", "mähdrescher", "landtechnik", "schlepper"),
    ("tierhaltung", "Tierhaltung", "agriculture", "nutztierhaltung", "melken", "tierpflege", "animal care", "zucht", "stallarbeit"),
    ("pflanzenschutz", "Pflanzenschutz", "agriculture", "düngung", "sachkundenachweis pflanzenschutz", "pflanzenbau", "gartenbau", "gärtner"),
    ("forst", "Forstwirtschaft", "agriculture", "waldarbeit", "motorsägenschein", "holzernte", "forestry"),
    ("umweltschutz", "Umweltschutz", "science", "nachhaltigkeit", "sustainability", "umweltmanagement", "iso 14001", "esg", "co2-bilanz", "energiemanagement"),
    # --- science and research -----------------------------------------------------------------------------
    ("forschung", "Forschung", "science", "research", "wissenschaftliches arbeiten", "publikationen", "studiendesign", "versuchsplanung", "drittmittel"),
    ("chemie", "Chemie", "science", "chemistry", "synthese", "hplc", "gc-ms", "spektroskopie", "titration", "chemielaborant"),
    ("biologie", "Biologie", "science", "biology", "mikrobiologie", "molekularbiologie", "pcr", "zellkultur", "biotechnologie"),
    ("physik", "Physik", "science", "physics", "optik", "lasertechnik", "vakuumtechnik", "messreihen"),
    ("pharma", "Pharmazeutische Industrie", "science", "gmp", "gxp", "validierung", "qualifizierung", "clinical trials", "klinische studien", "regulatory affairs", "pharmakovigilanz"),
    # --- security and safety ---------------------------------------------------------------------------------
    ("sachkunde34a", "Sachkundeprüfung §34a", "security", "sachkundeprüfung", "34a", "unterrichtung nach 34a", "bewachungsgewerbe"),
    ("objektschutz", "Objektschutz", "security", "werkschutz", "sicherheitsdienst", "security service", "revierdienst", "empfangsdienst", "veranstaltungsschutz", "doorman"),
    ("brandschutz", "Brandschutz", "security", "brandschutzhelfer", "fire safety", "evakuierung", "brandmeldeanlage", "feuerwehr"),
    ("arbeitssicherheit", "Arbeitssicherheit", "security", "unfallverhütung", "occupational safety", "arbeitsschutz", "sicherheitsvorschriften", "sifa", "gefährdungsbeurteilung", "psa"),
    ("videoueberwachung", "Videoüberwachung", "security", "leitstelle", "zutrittskontrolle", "alarmanlagen", "cctv"),
    # --- production and quality ------------------------------------------------------------------------------
    ("produktion", "Produktion", "production", "fertigung", "serienfertigung", "manufacturing", "maschinenbedienung", "maschinenführer", "anlagenführer", "produktionsplanung", "schichtführer"),
    ("qualitaetskontrolle", "Qualitätskontrolle", "production", "qualitätsprüfung", "quality control", "endkontrolle", "wareneingangsprüfung", "sichtprüfung", "prüfprotokolle"),
    ("verpackung", "Verpackung", "production", "abfüllung", "etikettierung", "packaging", "konfektionierung"),
    ("ruestung", "Rüsten", "production", "maschineneinrichtung", "werkzeugwechsel", "störungsbeseitigung"),
    # --- HR, office, administration ---------------------------------------------------------------------------
    ("personalwesen", "Personalwesen", "hr", "personalverwaltung", "human resources", "recruiting", "bewerbermanagement", "hr", "personalbetreuung", "onboarding", "personalentwicklung", "zeitwirtschaft"),
    ("sachbearbeitung", "Sachbearbeitung", "office", "büroorganisation", "administration", "verwaltung", "office management", "korrespondenz", "schriftverkehr", "aktenführung", "datenerfassung", "sekretariat", "assistenz der geschäftsführung"),
    ("terminplanung", "Terminplanung", "office", "kalenderverwaltung", "scheduling", "reiseplanung", "reisekostenabrechnung", "veranstaltungsorganisation"),
    ("einkauf", "Einkauf", "office", "beschaffung", "procurement", "lieferantenmanagement", "purchasing", "bestellabwicklung", "preisverhandlungen"),
    ("projectmanagement", "Projektmanagement", "office", "project management", "projektleitung", "projektsteuerung", "meilensteinplanung", "ressourcenplanung", "budgetverantwortung"),
    ("telefonzentrale", "Telefonzentrale", "office", "empfangstätigkeiten", "call center", "telefonische betreuung", "postbearbeitung"),
    ("immobilien", "Immobilien", "realestate", "makler", "real estate", "objektverwaltung", "hausverwaltung", "wohnungswirtschaft", "exposé", "mietverwaltung", "nebenkostenabrechnung", "wegverwaltung"),
    # --- sport and leisure -------------------------------------------------------------------------------------
    ("fitness", "Fitnesstraining", "sport", "trainingsplanung", "personal training", "gerätetraining", "kursleitung", "fitness", "trainerlizenz"),
    ("ernaehrungsberatung", "Ernährungsberatung", "sport", "ernährungswissenschaft", "nutrition", "diätetik", "diätassistenz"),
    ("schwimmen", "Rettungsschwimmen", "sport", "bademeister", "schwimmmeister", "dlrg", "aufsicht"),
    ("tourismus", "Tourismus", "sport", "reiseverkehr", "touristik", "reisebüro", "reiseleitung", "amadeus", "sabre"),
    # --- generic soft skills and conditions -----------------------------------------------------------------------
    ("teamfaehigkeit", "Teamfähigkeit", "soft", "teamarbeit", "teamwork", "teamplayer", "team player", "kooperationsfähigkeit"),
    ("zuverlaessigkeit", "Zuverlässigkeit", "soft", "zuverlässig", "reliability", "reliable", "pünktlichkeit", "verantwortungsbewusstsein"),
    ("sorgfalt", "Sorgfalt", "soft", "sorgfältig", "genauigkeit", "accuracy", "gewissenhaft", "detailgenauigkeit", "präzision", "liebe zum detail", "eye for detail", "attention to detail"),
    ("belastbarkeit", "Belastbarkeit", "soft", "belastbar", "resilience", "stressresistent", "körperliche belastbarkeit", "stressresistenz"),
    ("flexibilitaet", "Flexibilität", "soft", "flexibel", "flexibility", "anpassungsfähigkeit", "einsatzflexibilität"),
    ("kommunikationsfaehigkeit", "Kommunikationsfähigkeit", "soft", "kommunikationsstark", "communication skills", "ausdrucksfähigkeit", "verhandlungsgeschick", "überzeugungskraft"),
    ("selbststaendigkeit", "Selbstständige Arbeitsweise", "soft", "selbstständig", "eigenverantwortlich", "independent working", "eigeninitiative", "strukturierte arbeitsweise", "organisationsfähigkeit"),
    ("kundenorientierung", "Kundenorientierung", "soft", "serviceorientierung", "customer focus", "dienstleistungsorientiert", "freundliches auftreten"),
    ("empathie", "Empathie", "soft", "einfühlungsvermögen", "empathy", "geduld", "wertschätzung"),
    ("lernbereitschaft", "Lernbereitschaft", "soft", "weiterbildungsbereitschaft", "willingness to learn", "wissbegierig", "neugier"),
    ("analytisch", "Analytisches Denken", "soft", "analytical thinking", "problemlösungskompetenz", "lösungsorientiert", "konzeptionelles denken", "logisches denken"),
    ("fuehrungserfahrung", "Führungserfahrung", "soft", "teamleitung", "mitarbeiterführung", "leadership", "disziplinarische verantwortung", "personalverantwortung"),
    ("interkulturell", "Interkulturelle Kompetenz", "soft", "intercultural", "internationale zusammenarbeit"),
    ("schichtbereitschaft", "Schichtbereitschaft", "condition", "schichtarbeit", "schichtdienst", "shift work", "wochenendarbeit", "nachtdienst", "rufbereitschaft", "bereitschaftsdienst", "wechselschicht"),
    ("reisebereitschaft", "Reisebereitschaft", "condition", "montagebereitschaft", "willingness to travel", "dienstreisen", "außendiensttätigkeit"),
    ("koerperlichearbeit", "Körperliche Arbeit", "condition", "körperlich anspruchsvoll", "physical work", "heben und tragen", "stehende tätigkeit"),
    ("erscheinungsbild", "Gepflegtes Erscheinungsbild", "condition", "gepflegtes auftreten", "professional appearance", "sicheres auftreten"),
    ("polizeiliches", "Polizeiliches Führungszeugnis", "condition", "führungszeugnis", "einwandfreies führungszeugnis", "background check", "erweitertes führungszeugnis"),
    ("gesundheitszeugnis", "Gesundheitszeugnis", "condition", "belehrung nach infektionsschutzgesetz", "infektionsschutzgesetz", "arbeitsmedizinische vorsorge", "g25", "g41"),
    ("impfschutz", "Impfschutz", "condition", "masernschutz", "impfnachweis", "vaccination"),
    ("homeoffice_ready", "Homeoffice", "condition", "remote work", "mobiles arbeiten", "hybrides arbeiten"),
)


ALL_SKILLS: tuple[tuple[str, ...], ...] = IT_SKILLS + PROFESSION_SKILLS
